"use client";
import { useState } from 'react';
import Link from 'next/link';
import { TriangleDiagram, SquaresDiagram, RectangleDiagram, IsoscelesDiagram } from '@/components/maths/S2Chapter11Pythagoras';

const questions=[
 {q:'Triangle ABC is right-angled at B. Which side is the hypotenuse?',options:['AB','AC','BC'],answer:1,explanation:'AC is opposite the right angle at B. The position of the triangle on the page does not matter.'},
 {q:'The perpendicular sides are 5 cm and 12 cm. Find the hypotenuse.',options:['17 cm','7 cm','13 cm'],answer:2,explanation:'c² = 5² + 12² = 169 (Pyth. theorem), so c = 13 cm.'},
 {q:'The hypotenuse is 17 cm and one leg is 8 cm. Find the other leg.',options:['15 cm','9 cm','√353 cm'],answer:0,explanation:'x² + 8² = 17² (Pyth. theorem). Thus x² = 225 and x = 15 cm.'},
 {q:'Which equation is correct when c is the hypotenuse?',options:['c = a + b','a² + b² = c²','a² = b² + c²'],answer:1,explanation:'Add the squares of the perpendicular sides to obtain the square of the hypotenuse.'},
 {q:'A rectangle is 8 cm by 15 cm. Find its diagonal.',options:['23 cm','120 cm','17 cm'],answer:2,explanation:'d² = 8² + 15² = 289 (Pyth. theorem), so d = 17 cm.'},
 {q:'A square has side length 5 cm. Find its diagonal in exact form.',options:['√50 cm','10 cm','25 cm'],answer:0,explanation:'d² = 5² + 5² = 50 (Pyth. theorem). Hence d = √50 cm, also written 5√2 cm.'},
 {q:'The hypotenuse is 10 m and one leg is 6 m. Which working finds the other leg x?',options:['x² = 10² + 6²','x² = 10² − 6²','x = 10 − 6'],answer:1,explanation:'Start from x² + 6² = 10² (Pyth. theorem), then subtract 6². This gives x = 8 m.'},
 {q:'The perpendicular sides are 1.2 m and 50 cm. Find the hypotenuse in metres.',options:['51.2 m','√2501.44 m','1.3 m'],answer:2,explanation:'First convert 50 cm to 0.5 m. Then c² = 1.2² + 0.5² = 1.69, so c = 1.3 m.'},
 {q:'A right triangle has legs 2 cm and 5 cm. Find its hypotenuse to 3 significant figures.',options:['5.39 cm','5.38 cm','7.00 cm'],answer:0,explanation:'c = √(2² + 5²) = √29 = 5.385164… cm, which rounds to 5.39 cm.'},
 {q:'A student finds x² = 144 for a side length. What is x?',options:['±12 cm','12 cm','144 cm'],answer:1,explanation:'The positive square root is used because x is a length: x = 12 cm.'},
 {q:'An isosceles triangle has equal sides 13 cm and base 10 cm. Its perpendicular height bisects the base. Find the height.',options:['√69 cm','3 cm','12 cm'],answer:2,explanation:'Half the base is 5 cm. In one right triangle, h² + 5² = 13², so h² = 144 and h = 12 cm.'},
 {q:'A triangle has sides labelled a, b and c, but no right angle is given or established. Can you automatically use a² + b² = c²?',options:['No','Yes, for every triangle','Yes, if c looks longest'],answer:0,explanation:'Pythagoras’ theorem requires a right-angled triangle. Appearance alone is not sufficient.'},
];

export default function PythagorasLesson(){
 const [a,setA]=useState(3),[b,setB]=useState(4),[rotated,setRotated]=useState(false);
 const [responses,setResponses]=useState<Record<number,number>>({});
 const attempted=Object.keys(responses).length,correct=questions.filter((q,i)=>responses[i]===q.answer).length;
 return <main className="lesson"><Link href="/maths/s2/chapter-11">← Chapter 11 overview</Link>
 <header><p className="eyebrow">S2 · CHAPTER 11 · SECTION 11.2</p><h1>Pythagoras’ Theorem and its Applications</h1><p>Identify the right triangle, set up the equation and calculate the missing length.</p></header>
 <section><h2>Learning goals</h2><ul><li>Identify the hypotenuse even when a triangle is rotated.</li><li>Use Pythagoras’ theorem to find a hypotenuse or a perpendicular side.</li><li>Apply the theorem to diagonals, distances, heights and areas.</li><li>Keep exact values and round only when requested.</li></ul><p className="note">You will use square roots from Section 11.1. All lengths must use the same unit before calculation.</p></section>
 <section><h2>1. Find the hypotenuse first</h2><p>The <strong>hypotenuse</strong> is the side opposite the right angle. It is the longest side of a right-angled triangle. The other two sides meet at 90° and are called the perpendicular sides, or legs.</p><TriangleDiagram rotation={rotated?110:0}/><button type="button" aria-pressed={rotated} onClick={()=>setRotated(v=>!v)}>{rotated?'Show original orientation':'Rotate the triangle'}</button><p>The right angle is at C, so AB is the hypotenuse in both views. Here AC = a, BC = b and AB = c.</p><p className="warning">Do not identify the hypotenuse by “the sloping side”. Rotation changes the appearance, not the right angle or side relationships.</p></section>
 <section><h2>2. Pythagoras’ theorem</h2><p>For a right-angled triangle, the square of the hypotenuse equals the sum of the squares of the perpendicular sides.</p><p className="formula">a² + b² = c²</p><p className="reference">Reference: Pyth. theorem</p><p>With ∠ACB = 90°, the same statement can be written AC² + BC² = AB².</p><h3>Explore the areas of the three squares</h3><div className="grid"><div><label htmlFor="leg-a">Perpendicular side a: {a} units</label><input id="leg-a" type="range" min="2" max="6" step="1" value={a} onChange={e=>setA(Number(e.target.value))}/></div><div><label htmlFor="leg-b">Perpendicular side b: {b} units</label><input id="leg-b" type="range" min="2" max="6" step="1" value={b} onChange={e=>setB(Number(e.target.value))}/></div></div><SquaresDiagram a={a} b={b}/><p className="formula" role="status">{a}² + {b}² = {a*a} + {b*b} = {a*a+b*b} = c²</p><p>Each number inside a square is its area in square units. The two smaller square areas add to the largest square area.</p><p className="note">This is an illustration of the theorem, not its proof. Calculations in this lesson use the theorem as an established result.</p></section>
 <section><h2>3. Find the hypotenuse: add the squares</h2><p>In triangle ABC, ∠ACB = 90°, AC = 9 cm and BC = 12 cm. Find AB.</p><TriangleDiagram a={9} b={12} labels={['9 cm','12 cm','x']}/><div className="tableWrap"><table><caption>Example 1 · Find AB</caption><thead><tr><th>Working</th><th>Reference</th></tr></thead><tbody><tr><td>x² = 9² + 12²</td><td>Pyth. theorem</td></tr><tr><td>x² = 81 + 144 = 225</td><td>Arithmetic</td></tr><tr><td>x = √225 = 15</td><td>x &gt; 0, since x is a length</td></tr><tr><td>AB = 15 cm</td><td>State the answer with its unit</td></tr></tbody></table></div><p>Check: 15 cm is longer than either 9 cm or 12 cm, as a hypotenuse must be.</p><p className="note">The supplied Chapter Summary gives “Pyth. theorem”. Other Reference entries in these examples are explanatory reasons written for this lesson, not claimed textbook abbreviations.</p></section>
 <section><h2>4. Find a perpendicular side: subtract the squares</h2><p>In a right-angled triangle, the hypotenuse is 13 cm and one leg is 5 cm. Find the other leg x.</p><TriangleDiagram a={5} b={12} labels={['5 cm','x','13 cm']}/><div className="tableWrap"><table><caption>Example 2 · Find x</caption><thead><tr><th>Working</th><th>Reference</th></tr></thead><tbody><tr><td>5² + x² = 13²</td><td>Pyth. theorem</td></tr><tr><td>x² = 13² − 5² = 144</td><td>Rearrangement and arithmetic</td></tr><tr><td>x = √144 = 12 cm</td><td>x &gt; 0</td></tr></tbody></table></div><p className="warning">Write the full equation first. Do not subtract the side lengths: 13 − 5 is not the missing side.</p><div className="grid"><article><h3>Unknown hypotenuse</h3><p className="formula">c = √(a² + b²)</p></article><article><h3>Unknown leg</h3><p className="formula">a = √(c² − b²)</p></article></div><p>In both formulas, c must be the hypotenuse.</p></section>
 <section><h2>5. A rectangle’s diagonal</h2><p>Rectangle ABCD is 16 cm by 9 cm. Find diagonal AC in exact form, then correct to 3 significant figures.</p><RectangleDiagram/><div className="tableWrap"><table><caption>Example 3 · Find the diagonal</caption><thead><tr><th>Working</th><th>Reference</th></tr></thead><tbody><tr><td>∠ABC = 90°</td><td>ABCD is a rectangle</td></tr><tr><td>d² = 16² + 9² = 337</td><td>Pyth. theorem</td></tr><tr><td>d = √337 cm</td><td>d &gt; 0; exact value</td></tr><tr><td>d ≈ 18.4 cm (3 significant figures)</td><td>Round √337 = 18.357559…</td></tr></tbody></table></div><p>The diagonal divides the rectangle into two right-angled triangles. Use one of those triangles; do not use the perimeter.</p></section>
 <section><h2>6. Find a height, then an area</h2><p>In isosceles triangle ABC, AB = AC = 10 cm and BC = 12 cm. AD is perpendicular to BC, and D is the midpoint of BC. Find AD and the area of ABC.</p><IsoscelesDiagram/><div className="tableWrap"><table><caption>Example 4 · Two linked calculations</caption><thead><tr><th>Working</th><th>Reference</th></tr></thead><tbody><tr><td>BD = 12 ÷ 2 = 6 cm</td><td>D is given as the midpoint of BC</td></tr><tr><td>h² + 6² = 10²</td><td>Pyth. theorem, in right-angled triangle ABD</td></tr><tr><td>h² = 100 − 36 = 64</td><td>Rearrangement and arithmetic</td></tr><tr><td>AD = h = 8 cm</td><td>h &gt; 0</td></tr><tr><td>Area of ABC = ½ × 12 × 8 = 48 cm²</td><td>Area = ½ × base × perpendicular height</td></tr></tbody></table></div><p className="warning">Use half the base, 6 cm, in the right triangle. Use the whole base, 12 cm, when finding the area of the whole triangle.</p></section>
 <section><h2>7. Plan and check your solution</h2><ol><li>Identify a right angle from the stated information or established geometry. A sketch alone is not evidence.</li><li>Label the unknown length and identify the hypotenuse.</li><li>Convert all lengths to the same unit.</li><li>Write the squared-side equation and include “Pyth. theorem”.</li><li>Rearrange, calculate and take the positive square root.</li><li>Check that the hypotenuse is longest. Add units and round only at the end.</li></ol><h3>Distance example</h3><p>On a flat map, a route goes 6 km east and then 8 km north. These directions are perpendicular, so the straight-line distance between the start and finish is √(6² + 8²) = 10 km. The route travelled is 6 + 8 = 14 km: these are different quantities.</p><h3>Exact answers</h3><p>If the calculation gives x² = 41, write x = √41 unless a decimal approximation is requested. Do not round an intermediate length before using it in a second calculation.</p><p className="note">The converse, which checks whether given side lengths form a right-angled triangle, belongs to Section 11.3.</p></section>
 <section id="practice"><h2>8. Check your understanding</h2><p>Choose one answer per question. Read the explanation after answering, then restart for a fresh attempt.</p><p className="score" role="status">Answered {attempted} of {questions.length} · Correct {correct} of {attempted}</p><p className="note">This practice uses temporary page state only. It does not save progress, award XP or change Smart Review.</p>{questions.map((q,i)=><fieldset key={q.q}><legend>{i+1}. {q.q}</legend><div className="choices">{q.options.map((option,j)=><button key={option} type="button" aria-pressed={responses[i]===j} disabled={responses[i]!==undefined} onClick={()=>setResponses(previous=>previous[i]!==undefined?previous:{...previous,[i]:j})}>{option}</button>)}</div>{responses[i]!==undefined&&<p role="status" className={responses[i]===q.answer?'correct':'feedback'}><strong>{responses[i]===q.answer?'Correct. ':'Not quite. '}</strong>{q.explanation}</p>}</fieldset>)}{attempted===questions.length&&<p className="formula" role="status">Practice complete: {correct} / {questions.length}. {correct===questions.length?'You are ready to move on.':'Review the explanations before trying again.'}</p>}<button type="button" onClick={()=>{setResponses({});document.getElementById('practice')?.scrollIntoView({behavior:'smooth'});}}>Restart practice</button></section>
 <section><h2>Before you leave</h2><p>Can you explain when to add squares and when to subtract them? Can you locate the correct right triangle in a larger figure?</p><div className="choices"><Link href="/maths/s2/chapter-11/concept-of-nth-roots">← Section 11.1</Link><Link href="/maths/s2/chapter-11">Chapter 11 overview →</Link></div><p><Link href="/maths/s2/chapter-11/converse-of-pythagoras-theorem">Next: 11.3 Converse of Pythagoras’ Theorem and its Applications →</Link></p></section>
 <style jsx>{`
 .lesson{max-width:1080px;width:calc(100% - 32px);margin:36px auto 70px;color:#24364b;font:18px/1.65 Arial,sans-serif}.lesson *{box-sizing:border-box}.lesson :global(a){color:#0f766e;font-weight:700}header{padding:36px;background:#ecfeff;border:1px solid #a5f3fc;border-radius:26px;margin-top:22px}h1{font-size:clamp(32px,5vw,50px);line-height:1.2}h2{font-size:28px;line-height:1.3}h3{font-size:21px;line-height:1.4}.eyebrow{font-size:13px;font-weight:800;letter-spacing:.1em;color:#0e7490}section{padding:30px;border:1px solid #dce5ee;border-radius:22px;margin-top:24px;background:white}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:20px}.grid article{padding:22px;background:#f8fafc;border-radius:14px;min-width:0}.formula{padding:18px;background:#f5f3ff;color:#5b21b6;border-radius:12px;font-weight:700;overflow-wrap:anywhere}.reference{font-family:Georgia,serif;font-style:italic;color:#5b21b6}.note{font-size:15px;color:#52647a}.warning{background:#fff7ed;border-left:4px solid #c2410c;padding:16px}.tableWrap{overflow:auto;margin:22px 0}table{width:100%;border-collapse:collapse;text-align:left;font-size:16px}caption{text-align:left;font-weight:700;padding:8px 0}th,td{border:1px solid #dce5ee;padding:13px;vertical-align:top}th{background:#ecfeff}label{display:block;font-weight:700}input{width:100%;min-height:44px;accent-color:#0f766e}fieldset{min-width:0;margin:24px 0;padding:20px;border:1px solid #cbd5e1;border-radius:14px}legend{font-weight:700;padding:0 8px;max-width:100%}.choices{display:flex;flex-wrap:wrap;gap:12px}button{min-height:46px;padding:12px 18px;font:inherit;border:1px solid #0f766e;color:#0f766e;background:white;border-radius:12px;cursor:pointer}button[aria-pressed=true]{background:#0f766e;color:white}button:disabled{cursor:default}button:disabled:not([aria-pressed=true]){color:#52647a;border-color:#cbd5e1}.correct{color:#166534}.feedback{color:#9a3412}.score{font-weight:700}button:focus-visible,input:focus-visible,.lesson :global(a:focus-visible){outline:3px solid #d97706;outline-offset:3px}li{margin-bottom:8px}@media(max-width:720px){.grid{grid-template-columns:1fr}header,section{padding:22px}.lesson{font-size:17px}fieldset{padding:15px}th,td{padding:10px}}
 `}</style></main>;
}
