"use client";
import {useState} from "react";
import {Diagram,Segment,Vertex,Angle,type Point} from "@/components/maths/S2Chapter10Geometry";
import Link from "next/link";
const ref="the construction steps and the stated geometric reasons";
const questions=[
{q:"An angle of 74° is bisected. Find each resulting angle.",a:37,unit:"°",why:"An angle bisector divides an angle into two equal angles."},
{q:"AB is 12 cm long. Its perpendicular bisector meets AB at M. Find AM.",a:6,unit:"cm",why:"M is the midpoint, so AM = AB ÷ 2 = 6 cm."},
{q:"What angle does a perpendicular bisector make with its segment?",a:90,unit:"°",why:"Perpendicular lines meet at right angles."},
{q:"Bisect a constructed 60° angle. What angle results?",a:30,unit:"°",why:"60° ÷ 2 = 30°."},
{q:"Bisect a constructed right angle. What angle results?",a:45,unit:"°",why:"90° ÷ 2 = 45°."},
{q:"How many radius-length chords form a regular hexagon in a circle?",a:6,unit:"chords",why:"Each chord subtends 60° at the centre; six make 360°."},
{q:"A regular hexagon is inscribed in a circle of radius 5 cm. Find its side length.",a:5,unit:"cm",why:"Each side equals the circle radius."},
{q:"An equilateral triangle gives a 60° angle. Find its adjacent angle on a straight line.",a:120,unit:"°",why:"180° − 60° = 120° (adj. ∠s on st. line)."}
];
function CompassArc({c,r,start,end}:{c:Point;r:number;start:number;end:number}){const at=(d:number)=>({x:c.x+r*Math.cos(d*Math.PI/180),y:c.y+r*Math.sin(d*Math.PI/180)}),a=at(start),b=at(end);return <path d={`M${a.x} ${a.y} A${r} ${r} 0 ${end-start>180?1:0} 1 ${b.x} ${b.y}`} stroke="#0f766e" strokeWidth={1.7} fill="none"/>}
function Bisector({step}:{step:number}){const O={x:120,y:260},A={x:230,y:260},B={x:175,y:260-55*Math.sqrt(3)},C={x:285,y:260-55*Math.sqrt(3)};return <Diagram label={`Angle bisector construction, step ${step}. O is the vertex; equal-radius arcs from A and B meet at C.`} height={350}><Segment a={O} b={{x:400,y:260}}/><Segment a={O} b={{x:260,y:260-140*Math.sqrt(3)}}/><Vertex p={O} label="O" dx={-18} dy={20}/>{step>=1&&<><CompassArc c={O} r={110} start={-70} end={10}/><Vertex p={A} label="A" dx={0} dy={26}/><Vertex p={B} label="B" dx={-21} dy={-5}/></>}{step>=2&&<><CompassArc c={A} r={110} start={-75} end={-45}/><CompassArc c={B} r={110} start={-15} end={15}/><Vertex p={C} label="C" dx={22} dy={-12}/></>}{step>=3&&<><Segment a={O} b={{x:355,y:260-235/Math.sqrt(3)}}/><Angle v={O} a={A} b={C} r={35}/><Angle v={O} a={C} b={B} r={35}/></>}</Diagram>}
function Perp({step}:{step:number}){const A={x:170,y:180},B={x:350,y:180},h=Math.sqrt(120**2-90**2),P={x:260,y:180-h},Q={x:260,y:180+h};return <Diagram label={`Perpendicular bisector construction, step ${step}. Equal radius 120 arcs about endpoints 180 units apart intersect above and below AB.`} height={360}><Segment a={A} b={B}/><Vertex p={A} label="A" dx={-20} dy={7}/><Vertex p={B} label="B" dx={20} dy={7}/>{step>=1&&<><CompassArc c={A} r={120} start={-58} end={58}/><CompassArc c={B} r={120} start={122} end={238}/></>}{step>=2&&<><Vertex p={P} label="P" dx={44} dy={-12}/><Vertex p={Q} label="Q" dx={44} dy={22}/></>}{step>=3&&<><Segment a={{x:260,y:50}} b={{x:260,y:310}}/><path d="M260 166 H274 V180" stroke="#24364b" fill="none"/><Vertex p={{x:260,y:180}} label="M" dx={16} dy={26}/></>}</Diagram>}
function Hexagon(){const O={x:260,y:165},r=110,pts=Array.from({length:6},(_,i)=>({x:O.x+r*Math.cos(i*Math.PI/3),y:O.y+r*Math.sin(i*Math.PI/3)}));return <Diagram label="Regular hexagon inscribed in a circle. Each side equals the radius; the six central angles are 60 degrees." height={340}><circle cx={O.x} cy={O.y} r={r} fill="none" stroke="#0f766e" strokeWidth={1.5}/><polygon points={pts.map(p=>`${p.x},${p.y}`).join(' ')} fill="#f0fdfa" fillOpacity={0.65} stroke="#24364b" strokeWidth={2}/>{pts.map((p,i)=><g key={i}><Segment a={O} b={p} dashed/><Vertex p={p} label={'ABCDEF'[i]} dx={(p.x-O.x)/r*20} dy={(p.y-O.y)/r*20+5}/></g>)}<Angle v={O} a={pts[0]} b={pts[1]} r={28} label="60°" labelR={55}/><Vertex p={O} label="O" dx={-23} dy={-9}/></Diagram>}
function Demo({kind}:{kind:'angle'|'perp'}){const [step,setStep]=useState(0),steps=kind==='angle'?['Start with the given angle at O.','With centre O, draw one arc cutting the two rays at A and B. This makes OA = OB.','With centres A and B and the same radius AB, draw arcs that meet at C inside the angle, away from O.','Join O to C. OC is the angle bisector.']:['Start with the given segment AB.','Choose a radius greater than half AB. Without changing it, draw arcs centred at A and B, above and below AB.','Label the two arc intersections P and Q.','Join P and Q. Their line meets AB at M and is its perpendicular bisector.'];return <div>{kind==='angle'?<Bisector step={step}/>:<Perp step={step}/>}<p role="status">Step {step}: {steps[step]}</p><button disabled={step===0} onClick={()=>setStep(step-1)}>Previous step</button> <button disabled={step===3} onClick={()=>setStep(step+1)}>Next step</button> <button onClick={()=>setStep(0)}>Restart construction</button></div>}
function Practice(){const [values,setValues]=useState<string[]>(questions.map(()=>''));const [checked,setChecked]=useState(false);const correct=(i:number)=>values[i].trim()!==''&&Number.isFinite(Number(values[i]))&&Math.abs(Number(values[i])-questions[i].a)<0.000001;return <section><h2>Check your understanding</h2><p>Enter numbers only; the units are shown beside each box.</p>{questions.map((q,i)=><div className="question" key={q.q}><label htmlFor={'q'+i}>{i+1}. {q.q}</label><div><input id={'q'+i} type="text" inputMode="decimal" value={values[i]} onChange={e=>{setValues(values.map((v,j)=>j===i?e.target.value:v));setChecked(false)}}/> <span>{q.unit}</span></div>{checked&&<p>{correct(i)?'Correct.':values[i].trim()===''?'Not answered.':'Try again.'} {q.why}</p>}</div>)}<button onClick={()=>setChecked(true)}>Check answers</button> <button onClick={()=>{setValues(questions.map(()=>''));setChecked(false)}}>Reset</button>{checked&&<p role="status">{questions.filter((_,i)=>correct(i)).length} of {questions.length} correct. Use the reference: {ref}.</p>}</section>}
export default function Constructions(){return <main className="s2c10s4"><Link href="/maths/s2/chapter-10">← Chapter 10: Polygons</Link><header><p className="eyebrow">S2 · CHAPTER 10 · SECTION 10.4</p><h1>Constructions of Geometric Figures Using Compasses and a Straight Edge Only</h1><p>Construct exact relationships by transferring distances and intersecting arcs.</p></header>
<section><h2>1. What tools may we use?</h2><p>Use compasses to draw circles or arcs and transfer a distance. Use an unmarked straight edge to draw a line through two points.</p><p>Do not measure angles with a protractor or use ruler marks to locate a midpoint. Leave construction arcs visible so that the method can be checked.</p><p>On screen, the coordinates are calculated exactly. On paper, use the corresponding compass steps rather than copying distances from the screen.</p></section>
<section><h2>2. Construct an angle bisector</h2><Demo kind="angle"/><h3>Why does it work?</h3><table><thead><tr><th>Statement</th><th>Reference / reason</th></tr></thead><tbody><tr><td>OA = OB; AC = BC</td><td>Equal compass radii in each step</td></tr><tr><td>OC = OC</td><td>Common side</td></tr><tr><td>△OAC ≅ △OBC</td><td>SSS</td></tr><tr><td>∠AOC = ∠COB</td><td>corr. ∠s, ≅ △s</td></tr></tbody></table><p>OC divides the original angle into two equal angles. Choose the arc intersection inside the angle, not the original vertex O.</p></section>
<section><h2>3. Construct a perpendicular bisector</h2><Demo kind="perp"/><p>A perpendicular bisector passes through the midpoint of a segment and meets it at 90°.</p><p>The radius must be <strong>greater than half AB</strong>. A smaller radius gives no intersections; half AB gives only one touching point.</p><h3>Why does it work?</h3><p>PA = PB and QA = QB because of the equal radii. Both P and Q are equidistant from A and B, so PQ is the perpendicular bisector of AB.</p><p>Equivalently, SSS congruence gives equal angles on either side of PQ. The resulting triangles at M give AM = BM and equal adjacent angles of 90° [adj. ∠s on st. line].</p></section>
<section><h2>4. Construct perpendicular lines</h2><h3>At a point P on a line</h3><ol><li>With centre P, draw an arc meeting the line at A and B, one on each side of P.</li><li>Construct the perpendicular bisector of AB using equal-radius arcs from A and B.</li><li>Its line passes through P because PA = PB. This is the required perpendicular.</li></ol><h3>From a point P outside a line</h3><ol><li>With centre P, draw an arc large enough to cut the line at two distinct points A and B.</li><li>Construct the perpendicular bisector of AB.</li><li>That bisector passes through P because PA = PB, giving the required perpendicular from P to the line.</li></ol><p>Do not draw a line that merely looks vertical: perpendicularity is relative to the given line, which may be slanted.</p></section>
<section><h2>5. Construct a parallel line</h2><p>Given a line l and a point P outside it:</p><ol><li>Construct a line m through P perpendicular to l.</li><li>At P, construct a line k perpendicular to m.</li><li>Then k // l: two lines perpendicular to the same line in a plane are parallel.</li></ol><p>Written parallel notation is <strong>//</strong>, for example AB // CD. The two perpendicular constructions justify the result.</p></section>
<section><h2>6. Construct special angles</h2><table><thead><tr><th>Angle</th><th>Construction</th></tr></thead><tbody><tr><td>60°</td><td>On AB, draw circles with centres A and B and radius AB. Join an intersection C to A and B. △ABC is equilateral.</td></tr><tr><td>30°</td><td>Bisect the constructed 60° angle.</td></tr><tr><td>90°</td><td>Construct a perpendicular at a point on a line.</td></tr><tr><td>45°</td><td>Bisect the constructed 90° angle.</td></tr><tr><td>120°</td><td>Extend a side adjacent to a 60° angle: 180° − 60° = 120°.</td></tr></tbody></table><p>Reference for the 60° step: property of equil. △. Reference for the 120° step: adj. ∠s on st. line.</p></section>
<section><h2>7. Construct a square on a given side AB</h2><ol><li>Construct perpendiculars to AB at A and B.</li><li>With radius AB, mark D on the perpendicular at A and C on the perpendicular at B, on the same side of AB.</li><li>Join C to D. The square is ABCD in that order.</li></ol><p>AB = AD = BC by construction. AD // BC and both are perpendicular to AB; equal distances on these perpendiculars give the fourth side parallel and equal to AB. The result has four equal sides and four right angles.</p></section>
<section><h2>8. Construct a regular hexagon</h2><Hexagon/><ol><li>Draw a circle with centre O. Choose a starting point A on it.</li><li>Keep the compasses set to the circle radius.</li><li>Step off successive chords of that length around the circle, labelling B, C, D, E and F.</li><li>Join consecutive points, including F to A.</li></ol><p>Each centre–side triangle is equilateral, so each central angle is 60° [property of equil. △]. Six such angles make 360° [∠s at a pt.]. The hexagon side equals the radius.</p><p>If the final step does not return to A on paper, check that the compass opening did not change and redraw carefully.</p></section>
<section><h2>9. Check your paper construction</h2><ul><li>Keep the same radius wherever the instructions require it.</li><li>Use the actual arc intersections to place points.</li><li>Keep labels away from arcs and line intersections.</li><li>Leave the arcs visible and make the final lines clear.</li><li>Check both conditions of a perpendicular bisector: midpoint and right angle.</li></ul><p>The questions below check your understanding. Practise the actual constructions on paper too.</p></section><Practice/><p><Link href="/maths/s2/chapter-10/tessellation-of-figures">← Section 10.3</Link> · <Link href="/maths/s2/chapter-10">Chapter overview</Link></p><style jsx global>{`
.s2c10s4{max-width:1050px;width:calc(100% - 32px);margin:32px auto 70px;color:#24364b;font-family:Arial,sans-serif;line-height:1.7}.s2c10s4 *{box-sizing:border-box}.s2c10s4 a{color:#0f766e;font-weight:700}.s2c10s4 header{background:#ecfeff;border:1px solid #a5f3fc;padding:32px;border-radius:24px;margin-top:24px}.s2c10s4 h1{font-size:clamp(32px,5vw,48px);line-height:1.2}.s2c10s4 h2{font-size:27px;line-height:1.35}.s2c10s4 section{padding:28px;border:1px solid #dce5ee;border-radius:20px;background:#fff;margin:24px 0}.s2c10s4 .eyebrow{color:#0e7490;font-weight:700;font-size:13px;letter-spacing:.08em}.s2c10s4 svg{max-width:580px;margin:20px auto}.s2c10s4 .formula{background:#f5f3ff;color:#5b21b6;padding:16px;border-radius:12px;font-weight:700}.s2c10s4 .reference{font-family:Georgia,serif;font-style:italic}.s2c10s4 table{border-collapse:collapse;width:100%;table-layout:fixed}.s2c10s4 td,.s2c10s4 th{border:1px solid #dce5ee;padding:12px;text-align:left;overflow-wrap:anywhere}.s2c10s4 th{background:#f0fdfa}.s2c10s4 td:first-child,.s2c10s4 th:first-child{width:65%}.s2c10s4 label{display:block;font-weight:700}.s2c10s4 input[type=range]{width:100%;min-height:40px;accent-color:#0f766e}.s2c10s4 .question{padding:20px 0;border-bottom:1px solid #e2e8f0}.s2c10s4 input[type=text]{width:140px;padding:10px;font:inherit;border:1px solid #64748b;border-radius:8px;margin:10px 0}.s2c10s4 button{padding:12px 20px;border:1px solid #0f766e;background:#0f766e;color:white;font:inherit;border-radius:10px;margin-top:18px;cursor:pointer}.s2c10s4 button:focus-visible,.s2c10s4 input:focus-visible{outline:3px solid #d97706;outline-offset:3px}@media(max-width:600px){.s2c10s4 section,.s2c10s4 header{padding:18px}.s2c10s4 td,.s2c10s4 th{padding:8px;font-size:14px}}
`}</style></main>}
