"use client";
import { useState } from "react";
import Link from "next/link";
import { Diagram, Vertex, Angle, type Point } from "@/components/maths/S2Chapter9Geometry";
const shape:Point[]=[{x:0,y:0},{x:0,y:80},{x:100,y:80},{x:70,y:0}];
function SimilarPair({scale=1.5,reflected=false,worked=false}:{scale?:number;reflected?:boolean;worked?:boolean}){
 const first=shape.map(p=>({x:60+p.x,y:190-80+p.y}));
 const second=shape.map(p=>({x:reflected?470-p.x*scale:290+p.x*scale,y:190-(80-p.y)*scale}));
 return <Diagram label={`ABCD and EFGH are similar. Scale factor from ABCD to EFGH is ${scale}. ${reflected?'The second figure is reflected.':''}`} height={290}>{[first,second].map((points,j)=>{const centre=points.reduce((s,p)=>({x:s.x+p.x/4,y:s.y+p.y/4}),{x:0,y:0});return <g key={j}><polygon points={points.map(p=>`${p.x},${p.y}`).join(' ')} fill={j?'#f5f3ff':'#f0fdfa'} stroke="#24364b" strokeWidth={2.5}/>{points.map((p,i)=>{const dx=p.x-centre.x,dy=p.y-centre.y,d=Math.hypot(dx,dy);return <Vertex key={i} p={p} label={['ABCD','EFGH'][j][i]} dx={dx/d*22} dy={dy/d*22+5}/>;})}<Angle v={points[3]} a={points[0]} b={points[2]} r={18}/></g>;})}{worked&&<g fontFamily="Arial" fontSize={17} fill="#6d28d9" textAnchor="middle"><text x="30" y="156">8</text><text x="110" y="238">10</text><text x="260" y="140">12</text><text x="365" y="238">x</text></g>}<text x="110" y="270" textAnchor="middle" fontFamily="Arial" fontSize={17} fill="#24364b">ABCD</text><text x="375" y="270" textAnchor="middle" fontFamily="Arial" fontSize={17} fill="#24364b">EFGH</text></Diagram>;
}
type Row=readonly [string,string];
function Proof({rows}:{rows:readonly Row[]}){return <div className="proof"><table><thead><tr><th>Statement</th><th>Reference</th></tr></thead><tbody>{rows.map(([s,r],i)=><tr key={i}><td>{s}</td><td>{r}</td></tr>)}</tbody></table></div>;}
const exercises=[
 {q:'ABCD ∼ EFGH. AB = 6 cm and EF = 9 cm. Find the scale factor from ABCD to EFGH.',answer:1.5,unit:'',why:'EF/AB = 9/6 = 1.5.'},
 {q:'For the same figures, BC = 8 cm. Find FG.',answer:12,unit:'cm',why:'FG = 8 × 1.5 = 12 cm (Corresponding sides are proportional.).'},
 {q:'ABCD ∼ EFGH. ∠BCD = 112°. Find ∠FGH.',answer:112,unit:'°',why:'C corresponds to G, so ∠FGH = 112° (Corresponding angles are equal.).'},
 {q:'A figure is enlarged by scale factor 2.5. An image side is 20 cm. Find the original side.',answer:8,unit:'cm',why:'Original length = 20 ÷ 2.5 = 8 cm.'},
 {q:'Two similar figures have corresponding sides 15 cm and 6 cm. Find the scale factor from the larger to the smaller.',answer:0.4,unit:'',why:'Smaller/larger = 6/15 = 0.4.'},
 {q:'PQRS ∼ WXYZ. RS = 14 cm, PQ = 8 cm and WX = 12 cm. Find YZ.',answer:21,unit:'cm',why:'RS ↔ YZ. The scale factor is WX/PQ = 12/8 = 1.5, so YZ = 14 × 1.5 = 21 cm.'},
 {q:'A 4 cm by 7 cm rectangle is similar to a rectangle with shorter side 12 cm. Find the longer side.',answer:21,unit:'cm',why:'The scale factor is 12/4 = 3. The longer side is 7 × 3 = 21 cm.'},
 {q:'Similar polygons have scale factor 1.8 from A to B. The perimeter of A is 25 cm. Find the perimeter of B.',answer:45,unit:'cm',why:'Every side scales by 1.8, so the sum of the sides does too: 25 × 1.8 = 45 cm.'}
];
function correct(raw:string,n:number){return /^(?:\d+(?:\.\d*)?|\.\d+)$/.test(raw.trim())&&Math.abs(Number(raw)-n)<1e-9;}
export default function SectionNineFour(){const [scale,setScale]=useState(1.5),[reflected,setReflected]=useState(false),[values,setValues]=useState<Record<number,string>>({}),[checked,setChecked]=useState(false),[choice,setChoice]=useState<string|null>(null);return <main className="lesson"><Link href="/maths/s2/chapter-9">← Chapter 9</Link><header><p className="eyebrow">S2 · CHAPTER 9 · SECTION 9.4</p><h1>Similar Plane Figures</h1><p>Match corresponding parts, keep ratios in the same order and use a scale factor to find unknown lengths.</p></header>
<section><h2>1. Same shape, possibly different sizes</h2><p>For similar polygons, corresponding angles are equal and corresponding sides are proportional. Both conditions must hold.</p><p className="rule">ABCD ∼ EFGH</p><div className="choices">{[0.75,1,1.5].map(k=><button type="button" key={k} aria-pressed={scale===k} onClick={()=>setScale(k)}>Scale factor {k}</button>)}<button type="button" aria-pressed={reflected} onClick={()=>setReflected(v=>!v)}>Reflect second figure</button></div><SimilarPair scale={scale} reflected={reflected}/><p>EF/AB = FG/BC = GH/CD = HE/DA = {scale}.</p><p>{scale===1?'The figures are also congruent because the scale factor is 1.':scale<1?'The second figure is a reduction of the first.':'The second figure is an enlargement of the first.'}</p><p className="note">Reflection changes orientation but preserves the matching lengths and angles. Correspondence remains A ↔ E, B ↔ F, C ↔ G, D ↔ H.</p></section>
<section><h2>2. Keep the ratio direction consistent</h2><p>When going from ABCD to EFGH, use second figure ÷ first figure:</p><p className="rule">Scale factor k = EF/AB = FG/BC = GH/CD = HE/DA</p><p>Multiply an original length by k to get its image length. Divide an image length by k to recover the original.</p><p>Reversing the direction gives 1/k. If the forward factor is 3, the reverse factor is 1/3.</p></section>
<section><p className="eyebrow">WORKED EXAMPLE 1</p><h2>Find an unknown corresponding side</h2><p>ABCD ∼ EFGH. AB = 8, BC = 10 and EF = 12. Find x = FG.</p><SimilarPair worked/><Proof rows={[
 ['ABCD ∼ EFGH','given'],['FG/BC = EF/AB','Corresponding sides are proportional.'],['x/10 = 12/8',''],['∴ x = 15','']
]}/><p className="rule">FG corresponds to BC, not CD. Read the vertex order before writing the proportion.</p></section>
<section><p className="eyebrow">WORKED EXAMPLE 2</p><h2>Find an angle after reflection</h2><p>ABCD ∼ EFGH and ∠CDA = 110°. Find ∠GHE. The illustration shows the correspondence; do not measure it.</p><SimilarPair reflected/><Proof rows={[
 ['ABCD ∼ EFGH','given'],['∠GHE = ∠CDA','Corresponding angles are equal.'],['∴ ∠GHE = 110°','']
]}/><p className="note">Diagram not drawn to scale. Angles stay equal; do not multiply angles by the length scale factor.</p></section>
<section><h2>3. What is not sufficient?</h2><p>Two rectangles both have four right angles. A 2 × 3 rectangle and a 2 × 5 rectangle are not similar: the side ratios do not agree.</p><p>A square and a non-square rhombus can have equal corresponding side lengths but different angles. Side ratios alone do not establish similarity for general polygons.</p><p className="rule">AAA is a triangle similarity condition. Do not apply it to every polygon.</p><h3>Quick check</h3><p>Are all squares similar?</p><div className="choices">{['Yes','No'].map(v=><button type="button" key={v} aria-pressed={choice===v} onClick={()=>setChoice(v)}>{v}</button>)}</div>{choice&&<p role="status">{choice==='Yes'?'Correct.':'Try again.'} All corresponding angles are 90°, and all corresponding side ratios equal the ratio of the two side lengths.</p>}</section>
<section><h2>4. Perimeter scales like length</h2><p>If every side is multiplied by k, their sum is also multiplied by k. Therefore the perimeter is multiplied by k.</p><p>For example, a similar figure with scale factor 1.5 has perimeter 1.5 × 20 = 30 cm when the original perimeter is 20 cm.</p><p className="note">This is a length result. Area does not use the same multiplier.</p></section>
<section><h2>Try it on paper</h2><p>PQRS ∼ WXYZ. PQ = 5 cm, WX = 8 cm, RS = 7 cm and ∠QRS = 105°. Find YZ and ∠XYZ. Include references.</p><details><summary>Show model solution</summary><Proof rows={[
 ['YZ/RS = WX/PQ','Corresponding sides are proportional.'],['YZ/7 = 8/5',''],['∴ YZ = 11.2 cm',''],['∠XYZ = ∠QRS = 105°','Corresponding angles are equal.']
]}/></details></section>
<section><h2>Check your understanding</h2><p>Enter numbers only. Units are shown beside the answer boxes.</p>{exercises.map((e,i)=><article key={i}><label htmlFor={'q'+i}>{i+1}. {e.q}</label><div className="entry"><input id={'q'+i} inputMode="decimal" value={values[i]||''} onChange={event=>{setValues(v=>({...v,[i]:event.target.value}));setChecked(false);}}/><span>{e.unit}</span></div>{checked&&<p className="rule"><strong>{correct(values[i]||'',e.answer)?'Correct.':(values[i]||'').trim()?'Review this answer.':'Not answered.'}</strong> {e.why}</p>}</article>)}<div className="choices"><button type="button" onClick={()=>setChecked(true)}>Check answers</button><button type="button" onClick={()=>{setValues({});setChecked(false);}}>Start again</button></div><p role="status">{checked?`${exercises.filter((e,i)=>correct(values[i]||'',e.answer)).length} / 8 correct`:'Complete the questions, then check your answers.'}</p><p className="note">Answers reset when you leave or reload this page.</p></section><section><h2>Before moving on</h2><ul><li>Match vertices in the stated order.</li><li>Corresponding angles are equal.</li><li>Corresponding sides are proportional.</li><li>Keep the scale factor direction consistent.</li></ul><Link href="/maths/s2/chapter-9">← Back to Chapter 9</Link></section>
<style jsx>{`
.lesson{max-width:980px;width:calc(100% - 32px);margin:36px auto 70px;font-family:Arial,sans-serif;color:#24364b;line-height:1.65}.lesson *{box-sizing:border-box}.lesson :global(a){color:#0f766e;font-weight:700}header{padding:34px;background:#ecfdf5;border:1px solid #a7f3d0;border-radius:26px;margin-top:24px}h1{font-size:clamp(32px,5vw,48px);line-height:1.2}h2{font-size:28px;line-height:1.3}.eyebrow{font-size:13px;font-weight:800;letter-spacing:.1em;color:#0f766e}section{padding:30px;background:white;border:1px solid #dce5ee;border-radius:22px;margin-top:24px}.lesson :global(svg){max-width:650px;margin:20px auto}.lesson :global(.proof){overflow-x:auto}.lesson :global(table){width:100%;border-collapse:collapse;text-align:left;font-size:17px}.lesson :global(th),.lesson :global(td){padding:14px;border-bottom:1px solid #e2e8f0;vertical-align:top}.lesson :global(th){background:#f0fdfa}.lesson :global(td:last-child){border-left:1px solid #cbd5e1}.rule{background:#f5f3ff;border-radius:12px;padding:18px}.note{font-size:14px;color:#52647a}.choices{display:flex;gap:12px;flex-wrap:wrap}button{padding:12px 20px;font:inherit;font-weight:700;border:1px solid #0f766e;background:white;color:#0f766e;border-radius:12px;cursor:pointer}button[aria-pressed=true]{background:#0f766e;color:white}fieldset{border:1px solid #dce5ee;border-radius:14px;padding:18px;margin:24px 0}legend{font-weight:700;padding:0 6px}label{display:flex;gap:12px;align-items:center;padding:10px;cursor:pointer}input{width:19px;height:19px;accent-color:#0f766e;flex-shrink:0}summary{cursor:pointer;color:#0f766e;font-weight:700;padding:12px 0}button:focus-visible,input:focus-visible,summary:focus-visible{outline:3px solid #d97706;outline-offset:3px}@media(max-width:600px){header,section{padding:20px}.lesson :global(table){font-size:15px}.lesson :global(th),.lesson :global(td){padding:10px}}
 .entry{display:flex;gap:12px;align-items:center;margin:14px 0}.entry input{width:160px;height:auto;padding:12px;font:inherit;border:1px solid #94a3b8;border-radius:10px}article{padding:20px 0;border-bottom:1px solid #e2e8f0}
`}</style></main>;}
