create table if not exists public.knowledge_organiser_progress (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  student text not null,
  chapter_id text not null,
  taught_section_ids text[] not null default '{}',
  best_score integer not null default 0 check (best_score >= 0),
  best_max_score integer not null default 0 check (best_max_score >= 0),
  updated_at timestamptz not null default now(),
  unique (user_id, student, chapter_id)
);

alter table public.knowledge_organiser_progress enable row level security;

drop policy if exists "Students read own KO progress" on public.knowledge_organiser_progress;
create policy "Students read own KO progress"
on public.knowledge_organiser_progress for select
using (auth.uid() = user_id);

drop policy if exists "Students insert own KO progress" on public.knowledge_organiser_progress;
create policy "Students insert own KO progress"
on public.knowledge_organiser_progress for insert
with check (auth.uid() = user_id);

drop policy if exists "Students update own KO progress" on public.knowledge_organiser_progress;
create policy "Students update own KO progress"
on public.knowledge_organiser_progress for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);
