"use client";
import { useState } from "react";
import Link from "next/link";
import { Diagram, Segment, Vertex, Angle, Tick, ParallelMark } from "@/components/maths/S2Chapter9Geometry";
type Row = readonly [string,string];
function Proof({rows}:{rows:readonly Row[]}) {return <div className="proofWrap"><table><thead><tr><th>Statement</th><th>Reference</th></tr></thead><tbody>{rows.map(([s,r],i)=><tr key={i}><td>{s}</td><td className="reference">{r}</td></tr>)}</tbody></table></div>;}
function CongruenceDiagram({crossing=false}:{crossing?:boolean}) {
 if(crossing){const O={x:260,y:150},A={x:90,y:60},B={x:130,y:255},C={x:390,y:45},D={x:430,y:240};return <Diagram label="AOD and BOC are straight lines. OA equals OD and OB equals OC." height={310}>{[[A,D],[B,C],[A,B],[C,D]].map(([a,b],i)=><Segment key={i} a={a} b={b}/>)}<Tick a={O} b={A}/><Tick a={O} b={D}/><Tick a={O} b={B} count={2}/><Tick a={O} b={C} count={2}/><Angle v={O} a={A} b={B} r={27}/><Angle v={O} a={C} b={D} r={27}/><Vertex p={A} label="A" dx={-14} dy={-8}/><Vertex p={B} label="B" dx={-13} dy={25}/><Vertex p={C} label="C" dx={12} dy={-14}/><Vertex p={D} label="D" dx={17} dy={15}/><Vertex p={O} label="O" dy={-25}/></Diagram>;}
 const A={x:155,y:65},B={x:80,y:240},C={x:345,y:240},D={x:420,y:65};
 return <Diagram label="AD // BC, angles ABC and CDA are given equal, and AC is a shared diagonal." height={310}>{[[A,B],[B,C],[C,D],[D,A],[A,C]].map(([a,b],i)=><Segment key={i} a={a} b={b}/>)}<ParallelMark a={A} b={D}/><ParallelMark a={B} b={C}/><Angle v={B} a={A} b={C}/><Angle v={D} a={C} b={A}/><Vertex p={A} label="A" dy={-16}/><Vertex p={B} label="B" dx={-17} dy={20}/><Vertex p={C} label="C" dy={27}/><Vertex p={D} label="D" dx={17} dy={-8}/></Diagram>;
}
function SimilarityDiagram(){const A={x:160,y:38},B={x:75,y:278},C={x:440,y:278},D={x:109,y:182},E={x:328,y:182};return <Diagram label="D lies on AB, E lies on AC, and DE // BC. AD is 6, DB is 4, AE is 9, and EC is x. Lengths are not drawn to scale." height={340}>{[[A,B],[A,C],[B,C],[D,E]].map(([a,b],i)=><Segment key={i} a={a} b={b}/>)}<ParallelMark a={D} b={E}/><ParallelMark a={B} b={C}/><Angle v={D} a={A} b={E} r={22}/><Angle v={B} a={A} b={C} r={22}/><Vertex p={A} label="A" dy={-15}/><Vertex p={B} label="B" dx={-18} dy={21}/><Vertex p={C} label="C" dx={16} dy={18}/><Vertex p={D} label="D" dx={-24} dy={4}/><Vertex p={E} label="E" dx={21} dy={-3}/><g fill="#6d28d9" fontFamily="Arial" fontSize={19}><text x="110" y="107">6</text><text x="65" y="231">4</text><text x="263" y="108">9</text><text x="397" y="228">x</text></g></Diagram>;}
const aas:Row[]=[['∠ABC = ∠CDA','given'],['∠BCA = ∠DAC','alt. ∠s, AD // BC'],['AC = CA','common side'],['∴ △ABC ≅ △CDA','AAS'],['∴ AB = CD','corr. sides, ≅ Δs']];
const sas:Row[]=[['OA = OD','given'],['∠AOB = ∠DOC','vert. opp. ∠s'],['OB = OC','given'],['∴ △AOB ≅ △DOC','SAS'],['∴ AB = DC','corr. sides, ≅ Δs']];
const sim:Row[]=[['∠DAE = ∠BAC','common ∠'],['∠ADE = ∠ABC','corr. ∠s, DE // BC'],['∠AED = ∠ACB','corr. ∠s, DE // BC'],['∴ △ADE ∼ △ABC','AAA'],['AD/AB = AE/AC','corr. sides, ∼ Δs'],['6/(6 + 4) = 9/(9 + x)',''],['6(9 + x) = 90',''],['∴ x = 6','']];
const tasks=[
 {prompt:'In Example 1, choose the reference for ∠BCA = ∠DAC.',options:['alt. ∠s, AD // BC','common ∠','vert. opp. ∠s'],answer:0,explanation:'AC is a transversal of AD // BC. These are alternate angles.'},
 {prompt:'In Example 1, why is AC = CA?',options:['given','common side','corr. sides, ≅ Δs'],answer:1,explanation:'Both triangles contain the same segment AC. You can use this before proving congruence.'},
 {prompt:'Which vertex order matches △ABC in Example 1?',options:['△CAD','△DCA','△CDA'],answer:2,explanation:'A ↔ C, B ↔ D and C ↔ A, so write △ABC ≅ △CDA.'},
 {prompt:'Which condition completes Example 2?',options:['SSS','SAS','AAA'],answer:1,explanation:'Two equal side pairs surround the equal vertically opposite angle.'},
 {prompt:'After proving △AOB ≅ △DOC, choose the reference for AB = DC.',options:['corr. sides, ≅ Δs','given','common side'],answer:0,explanation:'The side equality follows from the established congruence.'},
 {prompt:'In Example 3, which ratio equals AE/AC?',options:['AD/DB','AB/AD','AD/AB'],answer:2,explanation:'Use small triangle / large triangle consistently. AB is AD + DB.'},
 {prompt:'May you write “corr. sides, ≅ Δs” before establishing congruence?',options:['Yes','No'],answer:1,explanation:'First establish congruence using a valid condition. Otherwise the reasoning is circular.'},
 {prompt:'Two triangles have three equal corresponding angles. What follows?',options:['They must be congruent','They are similar','Their corresponding sides must be equal'],answer:1,explanation:'AAA establishes similarity. The scale factor need not be 1.'}
];
export default function SectionNineOne(){const [answers,setAnswers]=useState<Record<number,number>>({}),[checked,setChecked]=useState(false);const score=tasks.filter((q,i)=>answers[i]===q.answer).length;
return <main className="lesson"><Link href="/maths/s2/chapter-9">← Chapter 9</Link><header><p className="eyebrow">S2 · CHAPTER 9 · SECTION 9.1</p><h1>Simple Proofs Involving Congruent Triangles and Similar Triangles</h1><p>Write each geometric statement with its reference. Match corresponding vertices before using equal sides or side ratios.</p></header>
<section><h2>A clear proof in four steps</h2><ol><li>Name the two triangles in corresponding order.</li><li>List the given facts and any angle or common-side facts.</li><li>State congruence or similarity and its condition.</li><li>Use corresponding parts to reach the required conclusion.</li></ol><div className="callout">Congruence: SSS, SAS, ASA, AAS, RHS.<br/>Similarity: AAA, SSS (equal side ratios), SAS (equal side ratios and equal included angle).</div><p>Equal-looking lengths or angles are not evidence. Use the stated information and established results.</p></section>
<section><p className="eyebrow">REFERENCE GUIDE</p><h2>Use short, precise references</h2><Proof rows={[
['Information stated in the question','given'],['The same side in both triangles','common side'],['The same angle in both triangles','common ∠'],['Vertically opposite angles are equal','vert. opp. ∠s'],['Alternate angles on parallel lines are equal','alt. ∠s, AD // BC'],['Corresponding angles on parallel lines are equal','corr. ∠s, DE // BC'],['Corresponding sides of congruent triangles are equal','corr. sides, ≅ Δs'],['Corresponding angles of congruent triangles are equal','corr. ∠s, ≅ Δs'],['Corresponding sides of similar triangles are proportional','corr. sides, ∼ Δs']
]}/><p className="note">Name the actual parallel lines in an angle reference. A blank reference is used below for routine substitution and algebra.</p></section>
<section><p className="eyebrow">WORKED EXAMPLE 1 · AAS</p><h2>Prove equal sides using parallel lines</h2><p>Given AD // BC and ∠ABC = ∠CDA, prove that AB = CD.</p><CongruenceDiagram/><p><strong>In △ABC and △CDA,</strong></p><Proof rows={aas}/><p className="callout">A ↔ C, B ↔ D, C ↔ A. The common side AC is not between the two angle pairs listed, so this proof uses AAS.</p></section>
<section><p className="eyebrow">WORKED EXAMPLE 2 · SAS</p><h2>Use the angle at an intersection</h2><p>AOD and BOC are straight lines. OA = OD and OB = OC. Prove that AB = DC.</p><CongruenceDiagram crossing/><p><strong>In △AOB and △DOC,</strong></p><Proof rows={sas}/><p className="callout">The angle at O is between the two equal side pairs. That is why SAS applies. SSA is not a general congruence condition.</p></section>
<section><p className="eyebrow">WORKED EXAMPLE 3 · AAA</p><h2>Prove similarity, then find a length</h2><p>D lies on AB, E lies on AC and DE // BC. Given AD = 6, DB = 4, AE = 9 and EC = x, find x.</p><SimilarityDiagram/><p className="note">Diagram not drawn to scale. Use the given lengths.</p><p><strong>In △ADE and △ABC,</strong></p><Proof rows={sim}/><p className="callout">Compare corresponding whole sides: AD with AB, and AE with AC. Here AB = 10 and AC = 9 + x. DB and EC are only the remaining parts.</p></section>
<section><h2>Try it on paper</h2><p>For the configuration in Example 2, prove ∠OAB = ∠ODC using the same givens. Write the triangle comparison, three facts, condition and conclusion.</p><details><summary>Show model proof</summary><p>In △AOB and △DOC,</p><Proof rows={[...sas.slice(0,4),['∴ ∠OAB = ∠ODC','corr. ∠s, ≅ Δs']]}/></details></section>
<section><h2>Check your references and reasoning</h2><p>Choose one answer for each question, then check your work.</p>{tasks.map((q,i)=><fieldset key={i}><legend>{i+1}. {q.prompt}</legend>{q.options.map((option,j)=><label key={option}><input type="radio" name={'q'+i} checked={answers[i]===j} onChange={()=>{setAnswers(a=>({...a,[i]:j}));setChecked(false);}}/>{option}</label>)}{checked&&<p className="feedback"><strong>{answers[i]===q.answer?'Correct.':answers[i]===undefined?'Not answered.':'Review this answer.'}</strong> {q.explanation}</p>}</fieldset>)}<div className="actions"><button type="button" onClick={()=>setChecked(true)}>Check answers</button><button type="button" onClick={()=>{setAnswers({});setChecked(false);}}>Start again</button></div><p role="status">{checked?`${score} / ${tasks.length} correct`:`${Object.keys(answers).length} / ${tasks.length} answered`}</p><p className="note">These practice answers reset when you leave or reload the page.</p></section>
<section><h2>Before moving on</h2><ul><li>I can match vertices and corresponding sides correctly.</li><li>I can name the reference for each angle or side statement.</li><li>I can use AAS or SAS to prove congruence.</li><li>I can use AAA to prove similarity before forming a proportion.</li></ul><Link href="/maths/s2/chapter-9">← Back to Chapter 9</Link></section>
<style jsx>{`
.lesson{max-width:980px;width:calc(100% - 32px);margin:36px auto 70px;font-family:Arial,sans-serif;color:#24364b;line-height:1.65}.lesson *{box-sizing:border-box}.lesson :global(a){color:#0f766e;font-weight:700}header{padding:34px;background:#ecfdf5;border:1px solid #a7f3d0;border-radius:26px;margin-top:24px}h1{font-size:clamp(30px,4.5vw,46px);line-height:1.2}h2{font-size:28px;line-height:1.3}.eyebrow{font-size:13px;font-weight:800;letter-spacing:.1em;color:#0f766e}section{padding:30px;background:white;border:1px solid #dce5ee;border-radius:22px;margin-top:24px}.lesson :global(svg){max-width:580px;margin:20px auto}.lesson :global(.proofWrap){overflow-x:auto}.lesson :global(table){width:100%;border-collapse:collapse;text-align:left;font-size:17px}.lesson :global(th),.lesson :global(td){padding:14px 16px;border-bottom:1px solid #e2e8f0;vertical-align:top}.lesson :global(th){background:#f0fdfa}.lesson :global(td.reference){font-family:Georgia,serif;font-style:italic;color:#52647a;border-left:1px solid #cbd5e1;width:38%}.callout,.feedback{background:#f5f3ff;border-radius:12px;padding:18px}.note{font-size:14px;color:#52647a}fieldset{border:1px solid #dce5ee;border-radius:14px;padding:18px;margin:24px 0}legend{font-weight:700;padding:0 6px}label{display:flex;align-items:center;gap:12px;padding:10px;cursor:pointer}input{width:19px;height:19px;accent-color:#0f766e;flex-shrink:0}.actions{display:flex;gap:12px;flex-wrap:wrap}button{padding:13px 22px;font:inherit;font-weight:700;border:1px solid #0f766e;background:#0f766e;color:white;border-radius:12px;cursor:pointer}button+button{background:white;color:#0f766e}summary{cursor:pointer;color:#0f766e;font-weight:700;padding:12px 0}button:focus-visible,input:focus-visible,summary:focus-visible{outline:3px solid #d97706;outline-offset:3px}@media(max-width:600px){header,section{padding:20px}.lesson :global(table){font-size:15px}.lesson :global(th),.lesson :global(td){padding:10px}.lesson :global(td.reference){width:40%}}
`}</style></main>;
}
