"use client";
import { reasonRef } from "@/data/maths/reasons/reasonBank";
import { DualReason, ReasonContent } from "@/components/maths/DualReason";


import { useState } from "react";
import Link from "next/link";
import { Diagram, Vertex, Angle, type Point } from "@/components/maths/S2Chapter9Geometry";
type Mode='translated'|'rotated'|'reflected';
const shape:Point[]=[{x:-60,y:-45},{x:-60,y:45},{x:60,y:45},{x:30,y:-45}];
function transform(p:Point,mode:Mode):Point {return mode==='rotated'?{x:-p.y,y:p.x}:mode==='reflected'?{x:-p.x,y:p.y}:p;}
function Pair({mode='translated',worked=false}:{mode?:Mode;worked?:boolean}){
 const left=shape.map(p=>({x:p.x+130,y:p.y+120})),right=shape.map(p=>{const t=transform(p,mode);return {x:t.x+385,y:t.y+120};});
 return <Diagram label={`ABCD and EFGH are congruent. The second figure is ${mode}. A corresponds to E, B to F, C to G and D to H.`} height={265}>{[left,right].map((points,j)=><g key={j}><polygon points={points.map(p=>`${p.x},${p.y}`).join(' ')} fill={j?'#f5f3ff':'#f0fdfa'} stroke="#24364b" strokeWidth={2.5}/>{points.map((p,i)=>{const centre={x:j?385:130,y:120},dx=p.x-centre.x,dy=p.y-centre.y,length=Math.hypot(dx,dy);return <Vertex key={i} p={p} label={['ABCD','EFGH'][j][i]} dx={dx/length*22} dy={dy/length*22+5}/>;})}<Angle v={points[3]} a={points[0]} b={points[2]} r={18}/></g>)}{worked&&<g fontFamily="Arial" fontSize={18} fill="#6d28d9"><text x="115" y="54" textAnchor="middle">6 cm</text><text x="370" y="54" textAnchor="middle">q cm</text></g>}<text x="130" y="236" textAnchor="middle" fontFamily="Arial" fontSize={17} fill="#24364b">ABCD</text><text x="385" y="236" textAnchor="middle" fontFamily="Arial" fontSize={17} fill="#24364b">EFGH</text></Diagram>;
}
function Rectangles(){return <Diagram label="A 6 by 4 rectangle and an 8 by 3 rectangle have equal area but are not congruent." height={240}><g fill="#f0fdfa" stroke="#24364b" strokeWidth={2.5}><rect x="55" y="60" width="144" height="96"/><rect x="270" y="60" width="192" height="72"/></g><g fontFamily="Arial" fontSize={18} fill="#24364b" textAnchor="middle"><text x="127" y="184">6 cm</text><text x="366" y="160">8 cm</text><text x="32" y="114">4</text><text x="488" y="102">3</text><text x="127" y="220">Area = 24 cm²</text><text x="366" y="220">Area = 24 cm²</text></g></Diagram>;}
type Row=readonly [string,string];
function Proof({rows}:{rows:readonly Row[]}){return <div className="proof"><table><thead><tr><th>Statement</th><th>Reason</th></tr></thead><tbody>{rows.map(([s,r],i)=><tr key={i}><td>{s}</td><td><ReasonContent>{r}</ReasonContent></td></tr>)}</tbody></table></div>;}
const questions=[
 {q:'ABCD ≅ EFGH. Which vertex corresponds to C?',options:['F','G','H'],answer:1,why:'Match the third letters: C ↔ G.'},
 {q:'ABCD ≅ EFGH. Which side corresponds to AD?',options:['EF','FG','EH'],answer:2,why:'A ↔ E and D ↔ H, so AD ↔ EH.'},
 {q:'ABCD ≅ EFGH. Which angle corresponds to ∠BCD?',options:['∠FGH','∠EFG','∠GHE'],answer:0,why:'B ↔ F, C ↔ G, D ↔ H. The middle letter is the angle vertex.'},
 {q:'A figure is reflected in a line. Is its image congruent to the original?',options:['Yes','No'],answer:0,why:'Reflection preserves all lengths and angles.'},
 {q:'Two polygons have equal area. Must they be congruent?',options:['Yes','No'],answer:1,why:'Equal area does not establish equal corresponding sides and angles.'},
 {q:'Two rectangles are 3 × 7 and 7 × 3. Are they congruent?',options:['Yes','No'],answer:0,why:'A quarter-turn matches their corresponding side lengths.'},
 {q:'Two quadrilaterals have four equal corresponding side lengths. Is that alone sufficient for congruence?',options:['Yes, by SSS','No'],answer:1,why:'SSS is a triangle condition. A square and a non-square rhombus may have equal side lengths but different angles.'},
 {q:'ABCD ≅ EFGH and BC = 12 cm. Find FG.',options:['6 cm','12 cm','24 cm'],answer:1,why:"BC and FG are corresponding sides of congruent figures, so FG = 12 cm." + reasonRef("figures.congruentSides")}
];
export default function SectionNineThree(){const [mode,setMode]=useState<Mode>('translated'),[answers,setAnswers]=useState<Record<number,number>>({}),[checked,setChecked]=useState(false);return <main className="lesson"><Link href="/maths/s2/chapter-9">← Chapter 9</Link><header><p className="eyebrow">S2 · CHAPTER 9 · SECTION 9.3</p><h1>Congruent Plane Figures</h1><p>Recognise figures with the same shape and size, and use corresponding sides and angles to find unknowns.</p></header>
<section><h2>1. Same shape and same size</h2><p>Two plane figures are congruent if one can fit exactly on the other after a translation, rotation or reflection. No enlargement or stretching is needed.</p><div className="choices">{(['translated','rotated','reflected'] as Mode[]).map(m=><button type="button" key={m} aria-pressed={mode===m} onClick={()=>setMode(m)}>{m==='translated'?'Translate':m==='rotated'?'Rotate 90°':'Reflect'}</button>)}</div><Pair mode={mode}/><p className="rule">ABCD ≅ EFGH</p><p>The labels move with their vertices. A ↔ E, B ↔ F, C ↔ G and D ↔ H in every view.</p><p className="note">A change of position or orientation does not change the shape or size.</p></section>
<section><h2>2. Read the order of the letters</h2><p>The statement ABCD ≅ EFGH tells us which parts correspond.</p><div className="proof"><table><thead><tr><th>Vertices</th><th>Sides</th><th>Angles</th></tr></thead><tbody>{[
 ['A ↔ E','AB ↔ EF','∠DAB ↔ ∠HEF'],['B ↔ F','BC ↔ FG','∠ABC ↔ ∠EFG'],['C ↔ G','CD ↔ GH','∠BCD ↔ ∠FGH'],['D ↔ H','DA ↔ HE','∠CDA ↔ ∠GHE']
].map(row=><tr key={row[0]}>{row.map(v=><td key={v}>{v}</td>)}</tr>)}</tbody></table></div><p className="rule">Match letters first. Do not match sides merely because they appear at the top, bottom, left or right.</p></section>
<section><h2>3. Properties of congruent figures</h2><ul><li>Corresponding sides are equal.</li><li>Corresponding angles are equal.</li></ul><p>For polygons, all corresponding side lengths and angles must match. Triangle tests such as SSS do not automatically apply to quadrilaterals.</p><h3>Worked example</h3><p>ABCD ≅ EFGH, AD = 6 cm and ∠ABC = 90°. Find q = EH and p = ∠EFG.</p><Pair worked/><Proof rows={[
 ['ABCD ≅ EFGH',reasonRef("geometry.given")],['EH = AD',reasonRef("figures.congruentSides")],['∴ q = 6',''],['∠EFG = ∠ABC',reasonRef("figures.congruentAngles")],['∴ p = 90°','']
]}/><p className="note">For plane figures, use the book’s references “Corresponding sides are equal.” and “Corresponding angles are equal.” The triangle symbol Δ is not used for these quadrilaterals.</p></section>
<section><h2>4. Avoid misleading shortcuts</h2><h3>Equal area is not enough</h3><Rectangles/><p>Both rectangles have area 24 cm², but their side lengths do not match. They are not congruent.</p><h3>Equal perimeter is not enough</h3><p>A 2 × 6 rectangle and a 3 × 5 rectangle both have perimeter 16 units. They are not congruent.</p><h3>Equal angles alone are not enough</h3><p>All rectangles have four right angles, but rectangles of different sizes need not be congruent.</p></section>
<section><h2>Try it on paper</h2><p>PQRS ≅ WXYZ. Given QR = 8 cm and ∠SPQ = 110°, find XY and ∠ZWX. Write Statement / Reason columns.</p><details><summary>Show model solution</summary><Proof rows={[
 ['PQRS ≅ WXYZ',reasonRef("geometry.given")],['XY = QR = 8 cm',reasonRef("figures.congruentSides")],['∠ZWX = ∠SPQ = 110°',reasonRef("figures.congruentAngles")]
]}/></details></section>
<section><h2>Check your understanding</h2>{questions.map((q,i)=><fieldset key={i}><legend>{i+1}. {q.q}</legend>{q.options.map((v,j)=><label key={v}><input type="radio" name={'q'+i} checked={answers[i]===j} onChange={()=>{setAnswers(a=>({...a,[i]:j}));setChecked(false);}}/>{v}</label>)}{checked&&<p className="rule"><strong>{answers[i]===q.answer?'Correct.':answers[i]===undefined?'Not answered.':'Review this answer.'}</strong> <ReasonContent>{q.why}</ReasonContent></p>}</fieldset>)}<div className="choices"><button type="button" onClick={()=>setChecked(true)}>Check answers</button><button type="button" onClick={()=>{setAnswers({});setChecked(false);}}>Start again</button></div><p role="status">{checked?`${questions.filter((q,i)=>answers[i]===q.answer).length} / 8 correct`:`${Object.keys(answers).length} / 8 answered`}</p><p className="note">Your answers reset when you leave or reload this page.</p></section><section><h2>Before moving on</h2><p>I can recognise congruent figures after turning or reflection, match vertices in order, and use equal corresponding parts with the correct reference.</p><Link href="/maths/s2/chapter-9">← Back to Chapter 9</Link></section>
<style jsx>{`
.lesson{max-width:980px;width:calc(100% - 32px);margin:36px auto 70px;font-family:Arial,sans-serif;color:#24364b;line-height:1.65}.lesson *{box-sizing:border-box}.lesson :global(a){color:#0f766e;font-weight:700}header{padding:34px;background:#ecfdf5;border:1px solid #a7f3d0;border-radius:26px;margin-top:24px}h1{font-size:clamp(32px,5vw,48px);line-height:1.2}h2{font-size:28px;line-height:1.3}.eyebrow{font-size:13px;font-weight:800;letter-spacing:.1em;color:#0f766e}section{padding:30px;background:white;border:1px solid #dce5ee;border-radius:22px;margin-top:24px}.lesson :global(svg){max-width:650px;margin:20px auto}.lesson :global(.proof){overflow-x:auto}.lesson :global(table){width:100%;border-collapse:collapse;text-align:left;font-size:17px}.lesson :global(th),.lesson :global(td){padding:14px;border-bottom:1px solid #e2e8f0;vertical-align:top}.lesson :global(th){background:#f0fdfa}.lesson :global(td:last-child){border-left:1px solid #cbd5e1}.rule{background:#f5f3ff;border-radius:12px;padding:18px}.note{font-size:14px;color:#52647a}.choices{display:flex;gap:12px;flex-wrap:wrap}button{padding:12px 20px;font:inherit;font-weight:700;border:1px solid #0f766e;background:white;color:#0f766e;border-radius:12px;cursor:pointer}button[aria-pressed=true]{background:#0f766e;color:white}fieldset{border:1px solid #dce5ee;border-radius:14px;padding:18px;margin:24px 0}legend{font-weight:700;padding:0 6px}label{display:flex;gap:12px;align-items:center;padding:10px;cursor:pointer}input{width:19px;height:19px;accent-color:#0f766e;flex-shrink:0}summary{cursor:pointer;color:#0f766e;font-weight:700;padding:12px 0}button:focus-visible,input:focus-visible,summary:focus-visible{outline:3px solid #d97706;outline-offset:3px}@media(max-width:600px){header,section{padding:20px}.lesson :global(table){font-size:15px}.lesson :global(th),.lesson :global(td){padding:10px}}
`}</style></main>;}
