"use client";
import { useState } from "react";
import Link from "next/link";
const questions=[
{id:"equation",prompt:"Solve 3 : 5 = x : 20.",unit:"",answer:12,hint:"The second term has been multiplied by 4.",working:"5 × 4 = 20, so x = 3 × 4 = 12."},
{id:"cross",prompt:"Solve 7/9 = 21/x.",unit:"",answer:27,hint:"Cross-multiply: 7x = 9 × 21.",working:"7x = 189, so x = 27."},
{id:"map",prompt:"A map has scale 1 : 25 000. Two places are 6 cm apart on the map. Find the actual distance in kilometres.",unit:"km",answer:1.5,hint:"Multiply by 25 000, then convert centimetres to kilometres.",working:"6 × 25 000 = 150 000 cm = 1500 m = 1.5 km."},
{id:"drawing",prompt:"At scale 1 : 200, what drawing length represents an actual length of 18 m?",unit:"cm",answer:9,hint:"Convert 18 m to centimetres before dividing by 200.",working:"18 m = 1800 cm; 1800 ÷ 200 = 9 cm."},
{id:"scale",prompt:"A drawing length of 5 cm represents 15 m. Write the scale as 1 : n. Find n.",unit:"",answer:300,hint:"Convert the actual length to centimetres.",working:"5 : 1500 = 1 : 300, so n = 300."},
{id:"enlarge",prompt:"A diagram is enlarged at scale 3 : 1. An actual part is 4 mm long. Find its length in the diagram.",unit:"mm",answer:12,hint:"Drawing length is three times actual length.",working:"4 × 3 = 12 mm."},
{id:"direct",prompt:"y is directly proportional to x. When x = 4, y = 18. Find y when x = 10.",unit:"",answer:45,hint:"Find the constant y ÷ x.",working:"k = 18 ÷ 4 = 4.5. Then y = 4.5 × 10 = 45."},
{id:"inverse",prompt:"y is inversely proportional to x. When x = 3, y = 16. Find y when x = 8.",unit:"",answer:6,hint:"The product xy is constant.",working:"k = 3 × 16 = 48. Then y = 48 ÷ 8 = 6."},
{id:"pipes",prompt:"4 identical pipes fill a tank in 9 hours. How long will 6 pipes take? Assume constant equal flow rates and no water loss.",unit:"h",answer:6,hint:"For the same tank, number of pipes × time is constant.",working:"4 × 9 = 6 × t, so t = 36 ÷ 6 = 6 h."},
{id:"constant",prompt:"A direct-proportion table has pairs (x, y) = (2, 7), (4, 14), (6, 21). Find the constant y/x.",unit:"",answer:3.5,hint:"Divide y by x for any pair.",working:"7 ÷ 2 = 14 ÷ 4 = 21 ÷ 6 = 3.5."},
];
function matches(raw:string,answer:number){return /^\d+(?:\.\d+)?$/.test(raw.trim())&&Math.abs(Number(raw)-answer)<1e-9;}
function ProportionChart({inverse,x}:{inverse:boolean;x:number}){
const px=(v:number)=>65+v*40,py=(v:number)=>345-v*12,y=inverse?24/x:2*x;
const curve=Array.from({length:241},(_,i)=>{const t=1+i/24;return `${i===0?"M":"L"}${px(t)},${py(24/t)}`}).join(" ");
return <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 570 410" role="img" aria-label={`${inverse?'y = 24/x for positive x':'y = 2x'}. Selected point (${x}, ${y}). Both axes begin at zero.`} style={{width:"100%",display:"block",minWidth:360}}>
{[0,4,8,12,16,20,24].map(n=><g key={n}><line x1="65" x2="505" y1={py(n)} y2={py(n)} stroke="#e1e8ef"/><text x="50" y={py(n)+5} textAnchor="end" fontSize="14" fill="#24364b">{n}</text></g>)}
{[0,2,4,6,8,10].map(n=><g key={n}><line x1={px(n)} x2={px(n)} y1="57" y2="345" stroke="#e1e8ef"/><text x={px(n)} y="368" textAnchor="middle" fontSize="14" fill="#24364b">{n}</text></g>)}
<path d="M65 45 V345 H520" fill="none" stroke="#24364b" strokeWidth="2"/><text x="535" y="350" fontSize="18">x</text><text x="60" y="30" fontSize="18">y</text>
<path d={inverse?curve:`M${px(0)},${py(0)} L${px(11)},${py(22)}`} stroke="#0f766e" strokeWidth="3" fill="none"/>
<path d={`M${px(x)},345 V${py(y)} H65`} stroke="#ad5918" strokeDasharray="6 5" fill="none"/><circle cx={px(x)} cy={py(y)} r="6" fill="#7040b8"/><text x="290" y="397" textAnchor="middle" fontSize="17" fill="#7040b8">{inverse?"xy = 24":"y/x = 2 (x ≠ 0)"}</text></svg>;
}
export default function ProportionsPage(){
const [inverse,setInverse]=useState(false),[x,setX]=useState(4),[choice,setChoice]=useState<string|null>(null),[answers,setAnswers]=useState<Record<string,string>>({}),[checked,setChecked]=useState<Record<string,boolean>>({});
const y=inverse?24/x:2*x,score=questions.filter(q=>checked[q.id]&&matches(answers[q.id]??"",q.answer)).length;
return <main className="proportionsPage"><Link className="back" href="/maths/s2/chapter-8">← Back to Chapter 8</Link><header><p className="eyebrow">S2 · CHAPTER 8 · SECTION 8.3</p><h1>Proportions</h1><p>Use equal ratios, interpret scale drawings and distinguish a constant ratio from a constant product.</p><div className="tags"><a href="#equal">Equal ratios</a><a href="#scale">Scale</a><a href="#explore">Explore</a><a href="#practice">Practise</a></div></header>
<section id="equal"><p className="eyebrow">1 · EQUAL RATIOS</p><h2>A proportion states that two ratios are equal</h2><div className="formula">a : b = c : d ⇔ a/b = c/d<br/>For b ≠ 0 and d ≠ 0: ad = bc</div><p>The products ad and bc are the cross-products. Multiplying both sides of a/b = c/d by bd gives ad = bc.</p><h3>Worked example</h3><p>Solve 4 : 7 = 12 : x.</p><ol><li>Write 4/7 = 12/x, where x ≠ 0.</li><li>Cross-multiply: 4x = 7 × 12 = 84.</li><li>Divide by 4: <strong>x = 21</strong>.</li><li>Check: 12 : 21 simplifies to 4 : 7.</li></ol><p className="note">Keep corresponding quantities in the same order. Cross-multiplication applies to an equality of fractions, not to any pair of unrelated ratios.</p></section>
<section id="scale"><p className="eyebrow">2 · SCALE DRAWINGS</p><h2>Compare drawing length with actual length</h2><div className="formula">Scale = drawing length ÷ actual length<br/>Use the same units for both lengths.</div><div className="grid"><article><h3>Reduction</h3><strong>1 : 100</strong><p>1 cm on the drawing represents 100 cm in reality.</p></article><article><h3>Actual size</h3><strong>1 : 1</strong><p>Drawing and actual lengths are equal.</p></article><article><h3>Enlargement</h3><strong>5 : 1</strong><p>5 mm on the drawing represents 1 mm in reality.</p></article></div><p>A scale may also be written as 1 : n. If n &gt; 1, it is a reduction; if 0 &lt; n &lt; 1, it is an enlargement.</p><h3>From a map to the actual distance</h3><p>A map scale is 1 : 20 000. A path measures 4.5 cm on the map.</p><div className="formula">Actual length = 4.5 × 20 000 = 90 000 cm<br/>90 000 cm = 900 m = 0.9 km</div><h3>From an actual length to a drawing</h3><p>A wall is 12 m long. Draw it at scale 1 : 150.</p><div className="formula">12 m = 1200 cm<br/>Drawing length = 1200 ÷ 150 = 8 cm</div><p className="note">The scale is a length ratio. Do not apply the length multiplier directly to an area or volume.</p></section>
<section><p className="eyebrow">3 · DIRECT PROPORTION</p><h2>The ratio stays constant</h2><p>For positive quantities in direct proportion, y = kx, where k is constant. Therefore y/x = k. Multiplying x by a factor multiplies y by that same factor.</p><div className="formula">y₁/x₁ = y₂/x₂</div><p>At a fixed price, 3 identical tickets cost $24. For 7 tickets:</p><ol><li>Cost per ticket = 24 ÷ 3 = $8.</li><li>Cost = 8 × 7 = <strong>$56</strong>.</li></ol><p>On a coordinate graph, y = kx is a straight line through the origin.</p></section>
<section><p className="eyebrow">4 · INVERSE PROPORTION</p><h2>The product stays constant</h2><p>For positive quantities in inverse proportion, xy = k, or y = k/x. Multiplying x by a factor divides y by that factor.</p><div className="formula">x₁y₁ = x₂y₂</div><p>5 identical printers complete a fixed job in 12 minutes. How long would 3 printers take, assuming equal constant rates and that the work can be shared?</p><ol><li>Constant product = 5 × 12 = 60 printer-minutes.</li><li>Time = 60 ÷ 3 = <strong>20 minutes</strong>.</li></ol><p className="note">This model needs the stated assumptions. More machines do not always divide the time exactly in a real job.</p></section>
<section id="explore"><p className="eyebrow">5 · INTERACTIVE COMPARISON</p><h2>Change x and watch the relationship</h2><div className="choices"><button type="button" aria-pressed={!inverse} onClick={()=>setInverse(false)}>Direct: y = 2x</button><button type="button" aria-pressed={inverse} onClick={()=>setInverse(true)}>Inverse: y = 24/x</button></div><label htmlFor="xValue">Choose x</label><select id="xValue" value={x} onChange={e=>setX(Number(e.target.value))}>{[1,2,3,4,6,8].map(n=><option key={n}>{n}</option>)}</select><p className="formula" aria-live="polite">x = {x} · y = {y}<br/>{inverse?`${x} × ${y} = 24`:`${y} ÷ ${x} = 2`}</p><div className="diagram"><ProportionChart inverse={inverse} x={x}/></div><p>{inverse?"Both axes start at 0, but y = 24/x is undefined at x = 0. The visible curve starts at x = 1; it does not join the origin.":"The graph passes through (0, 0). The quotient y/x is considered only when x is non-zero."}</p><div className="tableWrap"><table><caption>Check the invariant</caption><thead><tr><th>x</th>{[1,2,4,8].map(n=><th key={n}>{n}</th>)}</tr></thead><tbody><tr><th>y</th>{[1,2,4,8].map(n=><td key={n}>{inverse?24/n:2*n}</td>)}</tr><tr><th>{inverse?"xy":"y/x"}</th>{[1,2,4,8].map(n=><td key={n}>{inverse?24:2}</td>)}</tr></tbody></table></div></section>
<section><p className="eyebrow">6 · AVOID A COMMON TRAP</p><h2>Increasing together is not enough</h2><p>A table contains (x, y) = (1, 3), (2, 4), (3, 5). Are x and y directly proportional?</p><div className="choices">{["Yes","No"].map(c=><button type="button" key={c} aria-pressed={choice===c} onClick={()=>setChoice(c)}>{c}</button>)}</div>{choice&&<p role="status" className={choice==="No"?"success":"note"}>{choice==="No"?"Correct. y/x takes values 3, 2 and 5/3, so the ratio is not constant.":"Check y/x. Both increasing does not establish direct proportion."}</p>}<p>Likewise, one quantity decreasing while another increases does not prove inverse proportion: check their product.</p></section>
<section id="practice"><p className="eyebrow">7 · CHECK YOUR UNDERSTANDING</p><h2>Proportions practice</h2><p>Enter numbers only. The required units are shown.</p><p aria-live="polite"><strong>{score} of {questions.length} correct</strong></p>{questions.map((q,i)=><article className="question" key={q.id}><label htmlFor={q.id}>{i+1}. {q.prompt}</label><div className="answerRow"><input id={q.id} inputMode="decimal" value={answers[q.id]??""} aria-describedby={`${q.id}-unit`} onChange={e=>{setAnswers({...answers,[q.id]:e.target.value});setChecked({...checked,[q.id]:false})}}/><span id={`${q.id}-unit`}>{q.unit}</span><button type="button" onClick={()=>setChecked({...checked,[q.id]:true})}>Check</button></div>{checked[q.id]&&<p role="status" className={matches(answers[q.id]??"",q.answer)?"success":"note"}>{matches(answers[q.id]??"",q.answer)?`Correct. ${q.working}`:`Not yet. ${q.hint}`}</p>}<details><summary>Show worked solution</summary><p>{q.working}</p></details></article>)}<button type="button" onClick={()=>{setAnswers({});setChecked({})}}>Reset practice</button><p className="note">These answers are for this page session and reset on reload.</p></section>
<section className="summary"><p className="eyebrow">SECTION SUMMARY</p><h2>Choose the relationship before calculating</h2><ul><li>Equal ratios: check cross-products.</li><li>Scale: drawing length compared with actual length, in the same unit.</li><li>Direct proportion: constant y/x.</li><li>Inverse proportion: constant xy.</li></ul><Link className="back" href="/maths/s2/chapter-8">Finish Section 8.3 →</Link></section>
<style jsx>{`
.proportionsPage{max-width:1100px;width:calc(100% - 40px);margin:35px auto 70px;color:#24364b;font:17px/1.65 Arial,sans-serif}.proportionsPage *{box-sizing:border-box}.proportionsPage :global(.back){color:#0f766e;text-decoration:none;font-weight:700;display:inline-block;margin-bottom:20px}header{padding:38px;background:#fff4e5;border:1px solid #fed7aa;border-radius:25px}.eyebrow{color:#a64e10;font-size:13px;letter-spacing:.12em;font-weight:800;margin:0 0 12px}h1{font-size:clamp(38px,6vw,58px);line-height:1.1;margin:0 0 18px}h2{font-size:28px;line-height:1.3;margin:0 0 18px}h3{font-size:21px;margin:0 0 12px}section{padding:30px;border:1px solid #dce5ee;border-radius:22px;background:white;margin-top:24px;scroll-margin-top:20px}.grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:18px;margin:22px 0}.two{grid-template-columns:repeat(2,minmax(0,1fr))}.grid article{background:#f6f8fc;padding:22px;border-radius:15px}.formula{padding:20px;background:#edf9f5;color:#115e59;border-radius:14px;font-weight:700;font-size:20px;text-align:center}.note{background:#fff7ed;padding:15px;border-radius:12px;color:#85430f}.success{background:#e7f8ee;padding:15px;border-radius:12px;color:#12643a}.tags,.choices{display:flex;gap:12px;flex-wrap:wrap}.tags a{padding:8px 18px;background:white;color:#965016;border-radius:10px;text-decoration:none;font-weight:700}button{border:1px solid #6d3eb3;background:#6d3eb3;color:white;border-radius:10px;padding:11px 18px;font:inherit;font-weight:700;cursor:pointer}button[aria-pressed=true]{background:#0f766e;border-color:#0f766e}input{font:inherit;border:1px solid #94a3b8;border-radius:9px;padding:9px;min-width:0}input[type=range]{width:100%;display:block;accent-color:#0f766e;margin-top:15px}label{display:block;font-weight:700}.diagram{overflow-x:auto}.question{padding:24px;background:#f8fafc;border:1px solid #e1e8ef;border-radius:15px;margin:18px 0}.answerRow{display:flex;align-items:center;gap:12px;flex-wrap:wrap;margin-top:15px}.answerRow input{width:150px}details{margin-top:16px}summary{cursor:pointer;color:#6d3eb3;font-weight:700}.tableWrap{overflow-x:auto}table{width:100%;border-collapse:collapse;min-width:350px;margin-top:20px}th,td{padding:12px;border:1px solid #cbd5e1;text-align:center}th{background:#f0fdfa}select{font:inherit;padding:10px;border:1px solid #94a3b8;border-radius:10px;margin-top:10px}.summary{background:#f0fdfa}:focus-visible{outline:3px solid #ed9e34;outline-offset:3px}@media(max-width:750px){.grid,.two{grid-template-columns:1fr}header,section{padding:24px}}@media(max-width:450px){.proportionsPage{width:calc(100% - 24px);font-size:16px}header,section{padding:19px}.formula{font-size:18px}.question{padding:17px}}
`}</style></main>;
}
