"use client";
import { useState } from 'react';
import Link from 'next/link';
import { NumberFamilies, RootTwoConstruction } from '@/components/maths/S2Chapter11RealNumbers';
const examples=[
 {value:'−8',type:'Rational',reason:'−8 = −8/1. Every integer can be written with denominator 1.'},
 {value:'0.125',type:'Rational',reason:'0.125 = 125/1000 = 1/8. Every terminating decimal is rational.'},
 {value:'0.272727… (27 repeats)',type:'Rational',reason:'0.272727… = 27/99 = 3/11. The repeating block continues forever.'},
 {value:'√49',type:'Rational',reason:'√49 = 7 = 7/1. A root symbol does not automatically mean irrational.'},
 {value:'√7',type:'Irrational',reason:'7 is a positive integer that is not a perfect square, so √7 is irrational.'},
 {value:'π',type:'Irrational',reason:'π cannot be written as a ratio of two integers. Its decimal never terminates or eventually repeats.'},
 {value:'∛(−125)',type:'Rational',reason:'∛(−125) = −5 = −5/1.'},
 {value:'√(−4)',type:'Not a real number',reason:'In this course we work with real numbers. A negative number has no real square root, so this expression is neither a rational nor an irrational real number.'},
];
const questions=[
 {q:'Which statement defines a rational number?',options:['It can be written p/q, where p and q are integers and q ≠ 0.','It is always a positive whole number.','Its decimal never ends.'],answer:0,why:'A rational number is a ratio of two integers with a non-zero denominator.'},
 {q:'How should 0 be classified?',options:['Irrational','Rational','Not a real number'],answer:1,why:'0 = 0/1. A numerator may be zero; the denominator must not be zero.'},
 {q:'Which number is irrational?',options:['−4','0.625','√5'],answer:2,why:'−4 = −4/1 and 0.625 = 5/8. Since 5 is not a perfect square, √5 is irrational.'},
 {q:'Classify 0.454545… when the block 45 repeats forever.',options:['Rational','Irrational','Not a real number'],answer:0,why:'It is a repeating decimal: 0.454545… = 45/99 = 5/11.'},
 {q:'Which fraction equals 0.375?',options:['3/4','3/8','37/100'],answer:1,why:'0.375 = 375/1000 = 3/8.'},
 {q:'Which statement is correct?',options:['Every root is irrational.','Every non-terminating decimal is irrational.','Every integer is rational.'],answer:2,why:'An integer n equals n/1. Some roots are rational, and repeating non-terminating decimals are rational.'},
 {q:'Classify √(9/16).',options:['Rational','Irrational','Not a real number'],answer:0,why:'√(9/16) = 3/4, a ratio of two integers.'},
 {q:'Which statement about π and 22/7 is correct?',options:['π = 22/7 exactly.','π is irrational; 22/7 is a rational approximation.','Both are irrational.'],answer:1,why:'22/7 is a fraction of integers. It approximates π but is not equal to π.'},
 {q:'Classify the exact number 1.414.',options:['Irrational because it resembles √2','Not a real number','Rational'],answer:2,why:'1.414 = 1414/1000 = 707/500. This terminating decimal is rational, even though it approximates √2.'},
 {q:'Classify ∛64.',options:['Rational','Irrational','Not a real number'],answer:0,why:'∛64 = 4, an integer.'},
 {q:'Which decimal description guarantees an irrational number?',options:['Many digits are displayed.','It never terminates and never eventually repeats.','It is negative.'],answer:1,why:'An irrational real number has a decimal expansion that is non-terminating and not eventually periodic.'},
 {q:'How should √(−9) be classified in the real-number system?',options:['Rational','Irrational','Not a real number'],answer:2,why:'No real number has square −9. Irrational numbers are real numbers, so this is not an irrational real number.'},
 {q:'Classify √2 × √2.',options:['Rational','Irrational','Not a real number'],answer:0,why:'√2 × √2 = 2. Two irrational factors can have a rational product.'},
 {q:'A decimal starts 0.123456… but no rule for the later digits is given. Can you classify it from those digits alone?',options:['Yes, it must be irrational.','No, more information is needed.','Yes, it must be rational.'],answer:1,why:'A finite prefix does not tell us whether the full decimal eventually repeats.'},
 {q:'Which statement is correct?',options:['All rational numbers are integers.','A real number can be both rational and irrational.','Every real number is either rational or irrational, but not both.'],answer:2,why:'The two categories divide the real numbers. Integers form only part of the rational numbers.'},
];
export default function RationalIrrationalLesson(){
 const [selected,setSelected]=useState(0),[show,setShow]=useState(false),[answers,setAnswers]=useState<Record<number,number>>({});
 const item=examples[selected],attempted=Object.keys(answers).length,score=questions.filter((q,i)=>answers[i]===q.answer).length;
 return <main className="lesson"><Link href="/maths/s2/chapter-11">← Chapter 11 overview</Link><header><p className="eyebrow">S2 · CHAPTER 11 · SECTION 11.4</p><h1>Rational Numbers and Irrational Numbers</h1><p>Classify real numbers by their exact values, fractions and decimal expansions.</p></header>
 <section><h2>Learning goals</h2><ul><li>Define rational and irrational numbers.</li><li>Recognise terminating and recurring decimal expansions.</li><li>Evaluate roots before classifying them.</li><li>Distinguish an exact irrational number from a rational approximation.</li></ul></section>
 <section><h2>1. Rational numbers: ratios of integers</h2><p>A <strong>rational number</strong> can be written in the form p/q, where p and q are integers and q ≠ 0.</p><p className="formula">Rational number = p/q, with p, q integers and q ≠ 0</p><div className="grid"><article><h3>Integers belong here</h3><p>12 = 12/1</p><p>−7 = −7/1</p><p>0 = 0/1</p><p>Every integer is rational, including zero and negative integers.</p></article><article><h3>Fractions and decimals</h3><p>3/5 is rational.</p><p>−1.25 = −125/100 = −5/4</p><p>0.375 = 375/1000 = 3/8</p><p>A terminating decimal can be written over a power of 10.</p></article></div><p className="warning">The denominator must not be zero: 5/0 is undefined. A numerator of zero is allowed: 0/5 = 0.</p></section>
 <section><h2>2. Decimal expansions of rational numbers</h2><p>A rational number has a decimal expansion that either <strong>terminates</strong> or <strong>eventually repeats a fixed block of digits</strong>. “Recurring” and “repeating” mean the same thing here.</p><div className="tableWrap"><table><caption>Recognise the pattern</caption><thead><tr><th>Fraction</th><th>Decimal</th><th>Description</th></tr></thead><tbody><tr><td>3/8</td><td>0.375</td><td>Terminating</td></tr><tr><td>1/3</td><td>0.333…</td><td>3 repeats forever</td></tr><tr><td>2/11</td><td>0.181818…</td><td>18 repeats forever</td></tr><tr><td>1/6</td><td>0.1666…</td><td>After the first digit, 6 repeats forever</td></tr></tbody></table></div><p>The repeating block does not have to start immediately after the decimal point.</p><h3>Worked example: turn a recurring decimal into a fraction</h3><p>Let x = 0.272727…, where the block 27 repeats forever.</p><div className="tableWrap"><table><caption>Working and Reference</caption><thead><tr><th>Working</th><th>Reference</th></tr></thead><tbody><tr><td>x = 0.272727…</td><td>Define x</td></tr><tr><td>100x = 27.272727…</td><td>Multiply by 100 to align the repeating tails</td></tr><tr><td>100x − x = 27</td><td>Subtract the two equations</td></tr><tr><td>99x = 27</td><td>Collect like terms</td></tr><tr><td>x = 27/99 = 3/11</td><td>Divide by 99 and simplify</td></tr></tbody></table></div><p className="note">These Reference entries explain the algebra; they are not claimed textbook abbreviations.</p></section>
 <section><h2>3. Irrational numbers</h2><p>An <strong>irrational number</strong> is a real number that cannot be expressed as a ratio of two integers. Its decimal expansion never terminates and never eventually repeats a fixed block.</p><p className="formula">Examples: √2, √3, √5 and π</p><p>For a non-negative integer n, √n is rational exactly when n is a perfect square. For example, √36 = 6 is rational, while √37 is irrational.</p><p className="warning">“It goes on forever” is not enough: 0.333… goes on forever and is rational. You must also check whether the digits eventually repeat.</p><p>A finite calculator display cannot establish that a decimal never repeats. Classify the exact expression, not just the displayed digits.</p></section>
 <section><h2>4. How the number families fit together</h2><NumberFamilies/><p>Every real number is rational or irrational, but never both. Integers form a subset of the rational numbers. For example, 1/2 is rational but is not an integer.</p><p className="note">In the diagram, 0.333… means the digit 3 repeats forever. Box sizes do not represent how many numbers are in each group.</p><p>√(−4) has no real value. It is outside the real-number system considered here, so it is not an irrational real number.</p></section>
 <section><h2>5. Classify the value, not the symbol</h2><label htmlFor="example">Choose a number or expression</label><select id="example" value={selected} onChange={e=>{setSelected(Number(e.target.value));setShow(false);}}>{examples.map((e,i)=><option value={i} key={e.value}>{e.value}</option>)}</select><p className="formula">{item.value}</p><button type="button" onClick={()=>setShow(true)}>Reveal classification</button>{show&&<div role="status"><h3>{item.type}</h3><p>{item.reason}</p></div>}<h3>More worked examples</h3><div className="grid"><article><h3>Roots that are rational</h3><p>√(9/16) = 3/4</p><p>√0.04 = 0.2 = 1/5</p><p>∛(−125) = −5</p><p>Evaluate the root first, then classify.</p></article><article><h3>Expressions can simplify</h3><p>√2 × √2 = 2, which is rational.</p><p>√2 + (−√2) = 0, which is rational.</p><p>Two irrational numbers do not always give an irrational result when added or multiplied.</p></article></div></section>
 <section><h2>6. Irrational numbers have exact positions</h2><p>On a number line, an irrational number is a definite point. It is not an uncertain location or a “missing” number.</p><RootTwoConstruction/><p>A right triangle with perpendicular sides 1 and 1 has diagonal d satisfying d² = 1² + 1² = 2.</p><p className="reference">Reference: Pyth. theorem</p><p>Therefore d = √2. The circular arc transfers this length from the diagonal to the number line.</p><p className="formula">1² &lt; 2 &lt; 2², so 1 &lt; √2 &lt; 2.</p><p>The diagram explains a geometric length and its position; it is not a proof that √2 is irrational.</p></section>
 <section><h2>7. Exact numbers and approximations</h2><div className="tableWrap"><table><caption>Use = and ≈ carefully</caption><thead><tr><th>Expression</th><th>Classification</th><th>Reason</th></tr></thead><tbody><tr><td>√2</td><td>Irrational</td><td>2 is not a perfect square</td></tr><tr><td>1.414</td><td>Rational</td><td>1.414 = 707/500</td></tr><tr><td>π</td><td>Irrational</td><td>Not a ratio of two integers</td></tr><tr><td>3.14</td><td>Rational</td><td>3.14 = 157/50</td></tr><tr><td>22/7</td><td>Rational</td><td>Ratio of two integers</td></tr></tbody></table></div><p className="formula">√2 ≈ 1.414 &nbsp; and &nbsp; π ≈ 22/7</p><p>These are approximations, not exact equalities. A rational approximation does not make the original number rational.</p><p className="warning">A short digit string followed by “…” is not enough information unless the continuation is specified. Do not guess irrationality from a few unfamiliar digits.</p></section>
 <section id="practice"><h2>8. Check your understanding</h2><p>Choose one answer per question. Read the explanation, then restart for another attempt.</p><p role="status" className="score">Answered {attempted} of {questions.length} · Correct {score} of {attempted}</p><p className="note">Practice is temporary on this page. It does not save progress or award XP.</p>{questions.map((q,i)=><fieldset key={`question-${i}`}><legend>{i+1}. {q.q}</legend><div className="choices">{q.options.map((option,j)=><button key={option} type="button" disabled={answers[i]!==undefined} aria-pressed={answers[i]===j} onClick={()=>setAnswers(previous=>previous[i]!==undefined?previous:{...previous,[i]:j})}>{option}</button>)}</div>{answers[i]!==undefined&&<p role="status" className={answers[i]===q.answer?'correct':'feedback'}><strong>{answers[i]===q.answer?'Correct. ':'Not quite. '}</strong>{q.why}</p>}</fieldset>)}{attempted===questions.length&&<p role="status" className="formula">Practice complete: {score} / {questions.length}. {score===questions.length?'You are ready to move on.':'Review the explanations and try again.'}</p>}<button type="button" onClick={()=>{setAnswers({});document.getElementById('practice')?.scrollIntoView({behavior:'smooth'});}}>Restart practice</button></section>
 <section><h2>Before you leave</h2><p>Can you explain why 0.333… is rational, why √49 is rational, and why 1.414 is rational even though √2 is irrational?</p><div className="choices"><Link href="/maths/s2/chapter-11/converse-of-pythagoras-theorem">← Section 11.3</Link><Link href="/maths/s2/chapter-11">Chapter 11 overview →</Link></div><p><Link href="/maths/s2/chapter-11/operations-of-surds">Next: 11.5 Operations of Surds →</Link></p></section>
 <style jsx>{`
 .lesson{max-width:1080px;width:calc(100% - 32px);margin:36px auto 70px;color:#24364b;font:18px/1.65 Arial,sans-serif}.lesson *{box-sizing:border-box}.lesson :global(a){color:#0f766e;font-weight:700}header{padding:36px;background:#ecfeff;border:1px solid #a5f3fc;border-radius:26px;margin-top:22px}h1{font-size:clamp(32px,5vw,50px);line-height:1.2}h2{font-size:28px;line-height:1.3}h3{font-size:21px;line-height:1.4}.eyebrow{font-size:13px;font-weight:800;letter-spacing:.1em;color:#0e7490}section{padding:30px;border:1px solid #dce5ee;border-radius:22px;margin-top:24px;background:white}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:20px}.grid article{padding:22px;background:#f8fafc;border-radius:14px;min-width:0}.formula{padding:18px;background:#f5f3ff;color:#5b21b6;border-radius:12px;font-weight:700;overflow-wrap:anywhere}.reference{font-family:Georgia,serif;font-style:italic;color:#5b21b6}.note{font-size:15px;color:#52647a}.warning{background:#fff7ed;border-left:4px solid #c2410c;padding:16px}.tableWrap{overflow:auto;margin:22px 0}table{width:100%;border-collapse:collapse;text-align:left;font-size:16px}caption{text-align:left;font-weight:700;padding:8px 0}th,td{border:1px solid #dce5ee;padding:13px;vertical-align:top}th{background:#ecfeff}label{display:block;font-weight:700}select{max-width:100%;padding:12px;font:inherit;margin-top:12px}fieldset{min-width:0;margin:24px 0;padding:20px;border:1px solid #cbd5e1;border-radius:14px}legend{font-weight:700;padding:0 8px;max-width:100%}.choices{display:flex;flex-wrap:wrap;gap:12px}button{min-height:46px;padding:12px 18px;font:inherit;border:1px solid #0f766e;color:#0f766e;background:white;border-radius:12px;cursor:pointer}button[aria-pressed=true]{background:#0f766e;color:white}button:disabled{cursor:default}button:disabled:not([aria-pressed=true]){color:#52647a;border-color:#cbd5e1}.correct{color:#166534}.feedback{color:#9a3412}.score{font-weight:700}button:focus-visible,select:focus-visible,.lesson :global(a:focus-visible){outline:3px solid #d97706;outline-offset:3px}li{margin-bottom:8px}@media(max-width:720px){.grid{grid-template-columns:1fr}header,section{padding:22px}.lesson{font-size:17px}fieldset{padding:15px}th,td{padding:10px}}
 `}</style> </main>;
}
