import { Diagram,Segment,Vertex,Angle,Tick,ParallelMark,type Point } from "@/components/maths/S2Chapter9Geometry";
function CongruenceDiagram({crossing=false}:{crossing?:boolean}) {
 if(crossing){const O={x:260,y:150},A={x:90,y:60},B={x:130,y:255},C={x:390,y:45},D={x:430,y:240};return <Diagram label="AOD and BOC are straight lines. OA equals OD and OB equals OC." height={310}>{[[A,D],[B,C],[A,B],[C,D]].map(([a,b],i)=><Segment key={i} a={a} b={b}/>)}<Tick a={O} b={A}/><Tick a={O} b={D}/><Tick a={O} b={B} count={2}/><Tick a={O} b={C} count={2}/><Angle v={O} a={A} b={B} r={27}/><Angle v={O} a={C} b={D} r={27}/><Vertex p={A} label="A" dx={-14} dy={-8}/><Vertex p={B} label="B" dx={-13} dy={25}/><Vertex p={C} label="C" dx={12} dy={-14}/><Vertex p={D} label="D" dx={17} dy={15}/><Vertex p={O} label="O" dy={-25}/></Diagram>;}
 const A={x:155,y:65},B={x:80,y:240},C={x:345,y:240},D={x:420,y:65};
 return <Diagram label="AD // BC, angles ABC and CDA are given equal, and AC is a shared diagonal." height={310}>{[[A,B],[B,C],[C,D],[D,A],[A,C]].map(([a,b],i)=><Segment key={i} a={a} b={b}/>)}<ParallelMark a={A} b={D}/><ParallelMark a={B} b={C}/><Angle v={B} a={A} b={C}/><Angle v={D} a={C} b={A}/><Vertex p={A} label="A" dy={-16}/><Vertex p={B} label="B" dx={-17} dy={20}/><Vertex p={C} label="C" dy={27}/><Vertex p={D} label="D" dx={17} dy={-8}/></Diagram>;
}
function SimilarityDiagram(){const A={x:160,y:38},B={x:75,y:278},C={x:440,y:278},D={x:109,y:182},E={x:328,y:182};return <Diagram label="D lies on AB, E lies on AC, and DE // BC. AD is 6, DB is 4, AE is 9, and EC is x. Lengths are not drawn to scale." height={340}>{[[A,B],[A,C],[B,C],[D,E]].map(([a,b],i)=><Segment key={i} a={a} b={b}/>)}<ParallelMark a={D} b={E}/><ParallelMark a={B} b={C}/><Angle v={D} a={A} b={E} r={22}/><Angle v={B} a={A} b={C} r={22}/><Vertex p={A} label="A" dy={-15}/><Vertex p={B} label="B" dx={-18} dy={21}/><Vertex p={C} label="C" dx={16} dy={18}/><Vertex p={D} label="D" dx={-24} dy={4}/><Vertex p={E} label="E" dx={21} dy={-3}/><g fill="#6d28d9" fontFamily="Arial" fontSize={19}><text x="110" y="107">6</text><text x="65" y="231">4</text><text x="263" y="108">9</text><text x="397" y="228">x</text></g></Diagram>;}
function Triangle({kind}:{kind:'base'|'converse'|'equilateral'}){
 const base=kind==='equilateral'?60:kind==='base'?68:52,half=110,height=half*Math.tan(base*Math.PI/180),A={x:260,y:35},B={x:150,y:35+height},C={x:370,y:35+height};
 return <Diagram label={kind==='base'?'AB = AC. Angle B = 68 degrees. Find angle C and angle A.':kind==='converse'?'Angles B and C are both 52 degrees. AB = 7. Find AC.':'All three sides of ABC are equal. Find its interior angles.'} height={height+105}><Segment a={A} b={B}/><Segment a={A} b={C}/><Segment a={B} b={C}/>{kind!=='converse'&&<><Tick a={A} b={B}/><Tick a={A} b={C}/>{kind==='equilateral'&&<Tick a={B} b={C}/>}</>}<Angle v={B} a={A} b={C} label={kind==='equilateral'?'x':`${base}°`} labelR={53}/><Angle v={C} a={B} b={A} label={kind==='base'?'x':kind==='converse'?'52°':'y'} labelR={53}/>{kind!=='converse'&&<Angle v={A} a={B} b={C} label={kind==='base'?'y':'z'} labelR={55}/>}<Vertex p={A} label="A" dy={-15}/><Vertex p={B} label="B" dx={-17} dy={25}/><Vertex p={C} label="C" dx={17} dy={25}/>{kind==='converse'&&<g fontFamily="Arial" fontSize={19} fill="#6d28d9"><text x="177" y={35+height/2}>7</text><text x="335" y={35+height/2}>a</text></g>}</Diagram>;
}
type Mode='translated'|'rotated'|'reflected';
const shape:Point[]=[{x:-60,y:-45},{x:-60,y:45},{x:60,y:45},{x:30,y:-45}];
function transform(p:Point,mode:Mode):Point {return mode==='rotated'?{x:-p.y,y:p.x}:mode==='reflected'?{x:-p.x,y:p.y}:p;}
function Pair({mode='translated',worked=false}:{mode?:Mode;worked?:boolean}){
 const left=shape.map(p=>({x:p.x+130,y:p.y+120})),right=shape.map(p=>{const t=transform(p,mode);return {x:t.x+385,y:t.y+120};});
 return <Diagram label={`ABCD and EFGH are congruent. The second figure is ${mode}. A corresponds to E, B to F, C to G and D to H.`} height={265}>{[left,right].map((points,j)=><g key={j}><polygon points={points.map(p=>`${p.x},${p.y}`).join(' ')} fill={j?'#f5f3ff':'#f0fdfa'} stroke="#24364b" strokeWidth={2.5}/>{points.map((p,i)=>{const centre={x:j?385:130,y:120},dx=p.x-centre.x,dy=p.y-centre.y,length=Math.hypot(dx,dy);return <Vertex key={i} p={p} label={['ABCD','EFGH'][j][i]} dx={dx/length*22} dy={dy/length*22+5}/>;})}<Angle v={points[3]} a={points[0]} b={points[2]} r={18}/></g>)}{worked&&<g fontFamily="Arial" fontSize={18} fill="#6d28d9"><text x="115" y="54" textAnchor="middle">6 cm</text><text x="370" y="54" textAnchor="middle">q cm</text></g>}<text x="130" y="236" textAnchor="middle" fontFamily="Arial" fontSize={17} fill="#24364b">ABCD</text><text x="385" y="236" textAnchor="middle" fontFamily="Arial" fontSize={17} fill="#24364b">EFGH</text></Diagram>;
}
const scaledShape:Point[]=[{x:0,y:0},{x:0,y:80},{x:100,y:80},{x:70,y:0}];
function SimilarPair({scale=1.5,reflected=false,worked=false}:{scale?:number;reflected?:boolean;worked?:boolean}){
 const first=scaledShape.map(p=>({x:60+p.x,y:190-80+p.y}));
 const second=scaledShape.map(p=>({x:reflected?470-p.x*scale:290+p.x*scale,y:190-(80-p.y)*scale}));
 return <Diagram label={`ABCD and EFGH are similar. Scale factor from ABCD to EFGH is ${scale}. ${reflected?'The second figure is reflected.':''}`} height={290}>{[first,second].map((points,j)=>{const centre=points.reduce((s,p)=>({x:s.x+p.x/4,y:s.y+p.y/4}),{x:0,y:0});return <g key={j}><polygon points={points.map(p=>`${p.x},${p.y}`).join(' ')} fill={j?'#f5f3ff':'#f0fdfa'} stroke="#24364b" strokeWidth={2.5}/>{points.map((p,i)=>{const dx=p.x-centre.x,dy=p.y-centre.y,d=Math.hypot(dx,dy);return <Vertex key={i} p={p} label={['ABCD','EFGH'][j][i]} dx={dx/d*22} dy={dy/d*22+5}/>;})}<Angle v={points[3]} a={points[0]} b={points[2]} r={18}/></g>;})}{worked&&<g fontFamily="Arial" fontSize={17} fill="#6d28d9" textAnchor="middle"><text x="30" y="156">8</text><text x="110" y="238">10</text><text x="260" y="140">12</text><text x="365" y="238">x</text></g>}<text x="110" y="270" textAnchor="middle" fontFamily="Arial" fontSize={17} fill="#24364b">ABCD</text><text x="375" y="270" textAnchor="middle" fontFamily="Arial" fontSize={17} fill="#24364b">EFGH</text></Diagram>;
}
export type S2Chapter9DiagramKind='cross'|'similar'|'base'|'converse'|'equilateral'|'congruent'|'scaled';
export default function FlashDiagram({kind}:{kind:S2Chapter9DiagramKind}) {return <figure data-s2-c9-diagram={kind} style={{margin:'16px auto',width:'100%',maxWidth:560}}>{kind==='cross'?<CongruenceDiagram crossing/>:kind==='similar'?<SimilarityDiagram/>:kind==='congruent'?<Pair mode="reflected"/>:kind==='scaled'?<SimilarPair worked/>:<Triangle kind={kind}/>}</figure>;}
