import type {ReactNode} from 'react';
import {AngleArc,Segment} from './S2Chapter11Geometry';
type P={x:number;y:number};
const s=(a:number)=>Math.sin(a*Math.PI/180),c=(a:number)=>Math.cos(a*Math.PI/180);
function Label({p,children,dx=0,dy=0}:{p:P;children:ReactNode;dx?:number;dy?:number}){return <text x={p.x+dx} y={p.y+dy} textAnchor="middle" fill="#172d50" fontSize={18}>{children}</text>}
function Arc({p,a,b,label}:{p:P;a:P;b:P;label:string}){const bearing=(q:P)=>(Math.atan2(p.y-q.y,q.x-p.x)*180/Math.PI+360)%360;let start=bearing(a),end=bearing(b);if((end-start+360)%360>180)[start,end]=[end,start];if(end<start)end+=360;const m=(start+end)/2;return <><AngleArc centre={p} start={start} end={end} radius={24}/><Label p={{x:p.x+48*c(m),y:p.y-48*s(m)+5}}>{label}</Label></>}
function Frame({children,label}:{children:ReactNode;label:string}){return <svg viewBox="0 0 540 350" role="img" aria-label={label} style={{width:'100%',maxWidth:640,display:'block',margin:'20px auto'}}>{children}</svg>}
const dash=(a:P,b:P)=><line x1={a.x} y1={a.y} x2={b.x} y2={b.y} stroke="#0f766e" strokeWidth={2} strokeDasharray="6 4"/>;
export function SharedHeight(){
 const h=8*s(50),k=17,A={x:45,y:275},B={x:45+8*c(50)*k,y:275},D={x:B.x,y:275-h*k},C={x:B.x+Math.sqrt(400-h*h)*k,y:275};
 return <Frame label="A, B, C lie on a straight line. DB is perpendicular to AC. AD is 8 cm, DC is 20 cm, angle DAB is 50 degrees; theta is BDC."><Segment a={A} b={D}/><Segment a={D} b={C}/><Segment a={A} b={C}/>{dash(B,D)}<path d={`M ${B.x} 263 h 12 v 12`} fill="none" stroke="#0f766e"/><Arc p={A} a={B} b={D} label="50°"/><Arc p={D} a={B} b={C} label="θ"/>{[[A,'A'],[B,'B'],[C,'C']].map(([p,n])=><Label key={String(n)} p={p as P} dy={25}>{n as string}</Label>)}<Label p={D} dy={-17}>D</Label><Label p={{x:(A.x+D.x)/2-25,y:(A.y+D.y)/2}}>8 cm</Label><Label p={{x:(D.x+C.x)/2,y:(D.y+C.y)/2-18}}>20 cm</Label><Label p={{x:B.x+30,y:(B.y+D.y)/2+10}}>x cm</Label></Frame>;
}
export function AuxiliaryLines({show=true}:{show?:boolean}){
 const k=19,A={x:60,y:310},B={x:440,y:310},C={x:440,y:25},D={x:440-12*s(42)*k,y:25+12*c(42)*k},E={x:D.x,y:310},F={x:440,y:D.y};
 return <Frame label="AB is horizontal, BC vertical. AB 20, BC 15, CD 12, angle DCB 42 degrees. Add perpendiculars DE and DF to split the figure."><Segment a={A} b={B}/><Segment a={B} b={C}/><Segment a={C} b={D}/><Segment a={D} b={A}/><path d="M 428 310 v -12 h 12" fill="none" stroke="#0f766e"/>{show&&<>{dash(D,E)}{dash(D,F)}<path d={`M ${E.x-12} 310 v -12 h 12 M 440 ${F.y-12} h -12 v 12`} fill="none" stroke="#0f766e"/><Label p={E} dy={24}>E</Label><Label p={F} dx={20}>F</Label></>}<Arc p={A} a={B} b={D} label="θ"/><Arc p={C} a={D} b={B} label="42°"/><Label p={A} dx={-15} dy={12}>A</Label><Label p={B} dx={20} dy={12}>B</Label><Label p={C} dy={-9}>C</Label><Label p={D} dx={-16}>D</Label><Label p={{x:250,y:338}}>20</Label><Label p={{x:484,y:165}}>15</Label><Label p={{x:(C.x+D.x)/2-16,y:(C.y+D.y)/2-12}}>12</Label></Frame>;
}
export function MedianDiagram(){const A={x:420,y:55},B={x:100,y:295},C={x:420,y:295},M={x:260,y:295};return <Frame label="Right triangle ABC at C, AB 20 cm, BM and MC both 8 cm. AM joins A to the midpoint M."><Segment a={A} b={B}/><Segment a={B} b={C}/><Segment a={C} b={A}/><Segment a={A} b={M}/><path d="M 408 295 v -12 h 12" fill="none" stroke="#0f766e"/><Arc p={A} a={M} b={C} label="θ"/><Label p={A} dy={-16}>A</Label><Label p={B} dx={-18} dy={10}>B</Label><Label p={C} dx={18} dy={10}>C</Label><Label p={M} dy={25}>M</Label><Label p={{x:180,y:321}}>8 cm</Label><Label p={{x:340,y:321}}>8 cm</Label><Label p={{x:235,y:157}}>20 cm</Label><Label p={{x:465,y:185}}>h cm</Label></Frame>}
export function HeightDiagram({flag=false}:{flag?:boolean}){const deg=flag?60:35,base=flag?5:10*c(35),rise=flag?5*Math.tan(Math.PI/3):10*s(35),offset=flag?1.5:1.2,k=23,A={x:75,y:310-offset*k},B={x:75,y:310},D={x:75+base*k,y:A.y},E={x:D.x,y:A.y-rise*k},C={x:D.x,y:310};return <Frame label={flag?'Flagpole: horizontal distance 5 m, eye height 1.5 m, angle 60 degrees.':'Kite: straight string 10 m, hand height 1.2 m, angle above horizontal 35 degrees.'}><Segment a={B} b={C}/><Segment a={C} b={E}/><Segment a={A} b={E}/>{dash(A,D)}{dash(A,B)}<path d={`M ${D.x-12} ${D.y} v -12 h 12`} stroke="#0f766e" fill="none"/><Arc p={A} a={D} b={E} label={`${deg}°`}/><Label p={A} dx={-15} dy={-9}>{flag?'R':'A'}</Label><Label p={B} dy={23}>{flag?'C':'B'}</Label><Label p={C} dy={23}>{flag?'B':'C'}</Label><Label p={D} dx={20}>{flag?'Q':'D'}</Label><Label p={E} dy={-17}>{flag?'A':'E'}</Label><Label p={{x:35,y:(A.y+B.y)/2+4}}>{offset} m</Label>{flag?<Label p={{x:(B.x+C.x)/2,y:338}}>5 m</Label>:<Label p={{x:(A.x+E.x)/2-16,y:(A.y+E.y)/2-15}}>10 m</Label>}</Frame>}
export function BoardDiagram(){const k=24,Q={x:380,y:300-8*c(30)*k},R={x:284,y:300},P={x:380-6*c(30)*k,y:Q.y-3*k},S={x:R.x-6*c(30)*k,y:228},O={x:380,y:300},T={x:380,y:P.y};return <Frame label="Rectangle PQRS, PQ 6 cm and QR 8 cm, leans against vertical wall OQT. Angle OQR is 30 degrees; PT is horizontal."><polygon points={[P,Q,R,S].map(p=>`${p.x},${p.y}`).join(' ')} fill="#fff1cf" stroke="#172d50" strokeWidth={3}/><Segment a={O} b={T}/><Segment a={{x:90,y:300}} b={O}/>{dash(P,T)}<path d={`M 368 ${T.y} v 12 h 12 M 368 300 v -12 h 12`} fill="none" stroke="#0f766e"/><Arc p={Q} a={O} b={R} label="30°"/>{[[P,'P',-10,-14],[Q,'Q',20,6],[R,'R',-4,25],[S,'S',-20,0],[O,'O',20,12],[T,'T',20,0]].map(([p,n,dx,dy])=><Label key={String(n)} p={p as P} dx={dx as number} dy={dy as number}>{n as string}</Label>)}<Label p={{x:(P.x+Q.x)/2,y:(P.y+Q.y)/2-17}}>6 cm</Label><Label p={{x:(Q.x+R.x)/2-28,y:(Q.y+R.y)/2}}>8 cm</Label></Frame>}
