"use client";
import { useState } from "react";
import Link from "next/link";
const questions=[
 {id:"price",prompt:"6 notebooks cost $42. Find the price per notebook.",unit:"$/notebook",answer:7,hint:"Divide total cost by the number of notebooks.",working:"42 ÷ 6 = 7 dollars per notebook."},
 {id:"speed",prompt:"A cyclist travels 18 km in 45 minutes. Find the average speed.",unit:"km/h",answer:24,hint:"First convert 45 minutes to hours.",working:"45 ÷ 60 = 0.75 h; 18 ÷ 0.75 = 24 km/h."},
 {id:"distance",prompt:"A train averages 80 km/h for 1.5 hours. Find the distance travelled.",unit:"km",answer:120,hint:"Distance = average speed × time.",working:"80 × 1.5 = 120 km."},
 {id:"time",prompt:"A car travels 150 km at an average speed of 60 km/h. Find the journey time.",unit:"h",answer:2.5,hint:"Time = distance ÷ average speed.",working:"150 ÷ 60 = 2.5 h, which is 2 h 30 min."},
 {id:"convert",prompt:"Convert 54 km/h to metres per second.",unit:"m/s",answer:15,hint:"1 km = 1000 m; 1 h = 3600 s.",working:"54 × 1000 ÷ 3600 = 15 m/s."},
 {id:"flow",prompt:"A tap delivers 72 litres in 8 minutes at a constant rate. How much water does it deliver in 5 minutes?",unit:"L",answer:45,hint:"Find litres per minute, then multiply by 5.",working:"72 ÷ 8 = 9 L/min; 9 × 5 = 45 L."},
 {id:"average",prompt:"A bus travels 60 km in 1 hour, then 60 km in 2 hours. Find its average speed for the whole journey.",unit:"km/h",answer:40,hint:"Use total distance divided by total time.",working:"(60 + 60) ÷ (1 + 2) = 120 ÷ 3 = 40 km/h. Do not simply average 60 and 30."},
 {id:"reverse",prompt:"A printer produces 24 pages per minute. How many seconds does it take per page?",unit:"s/page",answer:2.5,hint:"One minute is 60 seconds.",working:"60 ÷ 24 = 2.5 seconds per page."},
];
function matches(raw:string,expected:number){return /^[+-]?(?:\d+(?:\.\d*)?|\.\d+)$/.test(raw.trim())&&Math.abs(Number(raw)-expected)<1e-8;}
function Journey({speed,hours}:{speed:number;hours:number}){const distance=speed*hours,px=(n:number)=>60+n/240*480;return <svg viewBox="0 0 600 160" role="img" aria-label={`Distance travelled: ${distance} kilometres. Scale from zero to 240 kilometres.`} style={{width:"100%",display:"block",minWidth:340}}><line x1="60" y1="75" x2="540" y2="75" stroke="#bac8d6" strokeWidth="5"/><line x1="60" y1="75" x2={px(distance)} y2="75" stroke="#0f766e" strokeWidth="6"/>{[0,60,120,180,240].map(n=><g key={n}><line x1={px(n)} x2={px(n)} y1="67" y2="84" stroke="#24364b"/><text x={px(n)} y="111" textAnchor="middle" fontSize="16" fill="#24364b">{n}</text></g>)}<circle cx={px(distance)} cy="75" r="7" fill="#7040b8"/><text x="300" y="30" textAnchor="middle" fontSize="20" fill="#7040b8">Distance = {distance} km</text><text x="300" y="145" textAnchor="middle" fontSize="16" fill="#24364b">Distance (km)</text></svg>}
export default function RatesPage(){
const [speed,setSpeed]=useState(60),[hours,setHours]=useState(1),[answers,setAnswers]=useState<Record<string,string>>({}),[checked,setChecked]=useState<Record<string,boolean>>({}),[choice,setChoice]=useState<string|null>(null);
const score=questions.filter(q=>checked[q.id]&&matches(answers[q.id]??"",q.answer)).length;
return <main className="ratesPage"><Link href="/maths/s2/chapter-8" className="back">← Back to Chapter 8</Link><header><p className="eyebrow">S2 · CHAPTER 8 · SECTION 8.1</p><h1>Rates</h1><p>Find an amount per unit, compare options fairly and connect distance, speed and time.</p><div className="tags"><a href="#meaning">Learn</a><a href="#explore">Explore</a><a href="#practice">Practise</a></div></header>
<section id="meaning"><p className="eyebrow">1 · THE MEANING OF A RATE</p><h2>“Per” means “for each one”</h2><p>A rate compares quantities of different kinds by division. It tells us how much of one quantity corresponds to one unit of another.</p><div className="formula">Rate = first quantity ÷ second quantity</div><div className="grid"><article><h3>Price rate</h3><strong>$36 ÷ 9 pens = $4/pen</strong><p>Each pen costs $4.</p></article><article><h3>Speed</h3><strong>120 km ÷ 2 h = 60 km/h</strong><p>The average distance per hour is 60 km.</p></article><article><h3>Water flow</h3><strong>30 L ÷ 5 min = 6 L/min</strong><p>Six litres are delivered per minute on average.</p></article></div><p className="note">Read the order carefully: dollars per pen is cost ÷ number of pens. Pens per dollar reverses the division and answers a different question.</p></section>
<section><p className="eyebrow">2 · UNITS MATTER</p><h2>Convert before you divide</h2><p>A cyclist travels 15 km in 30 minutes. To calculate km/h, write the time in hours.</p><ol><li>30 min = 30 ÷ 60 = 0.5 h.</li><li>Average speed = 15 ÷ 0.5 = <strong>30 km/h</strong>.</li></ol><p>The same journey gives 15 ÷ 30 = <strong>0.5 km/min</strong>. The number changes with the unit, but the physical rate is the same.</p><div className="grid two"><article><h3>km/h → m/s</h3><p>Multiply by 1000 and divide by 3600.</p><strong>72 km/h = 72 ÷ 3.6 = 20 m/s</strong></article><article><h3>m/s → km/h</h3><p>Multiply by 3600 and divide by 1000.</p><strong>5 m/s = 5 × 3.6 = 18 km/h</strong></article></div><p className="note">1 h 30 min = 1.5 h. It is not 1.30 h.</p></section>
<section><p className="eyebrow">3 · COMPARE UNIT PRICES</p><h2>Use the same amount for both options</h2><p>Compare two packs of identical exercise books.</p><div className="grid two"><article><h3>Pack A</h3><p>6 books for $30</p><strong>$30 ÷ 6 = $5/book</strong></article><article><h3>Pack B</h3><p>10 books for $45</p><strong>$45 ÷ 10 = $4.50/book</strong></article></div><p>Which pack has the lower price per book?</p><div className="choices">{["A","B"].map(c=><button key={c} type="button" aria-pressed={choice===c} onClick={()=>setChoice(c)}>Pack {c}</button>)}</div>{choice&&<p className={choice==="B"?"success":"note"} role="status">{choice==="B"?"Correct. Pack B is cheaper per book, even though its total price is higher.":"Compare $5 per book with $4.50 per book. The lower total price alone does not show the lower unit price."}</p>}</section>
<section id="explore"><p className="eyebrow">4 · DISTANCE, SPEED AND TIME</p><h2>Build a journey</h2><div className="formula">Average speed = total distance ÷ total time<br/>Distance = average speed × time<br/>Time = distance ÷ average speed</div><div className="grid two"><label>Speed: <strong>{speed} km/h</strong><input type="range" min="20" max="80" step="10" value={speed} onChange={e=>setSpeed(Number(e.target.value))}/></label><label>Time: <strong>{hours} h</strong><input type="range" min="0.5" max="3" step="0.5" value={hours} onChange={e=>setHours(Number(e.target.value))}/></label></div><div className="diagram"><Journey speed={speed} hours={hours}/></div><p className="formula" aria-live="polite">{speed} km/h × {hours} h = {speed*hours} km</p><p>The diagram uses a fixed scale. At a constant speed, twice as much time gives twice the distance.</p><h3>Finding time</h3><p>A coach covers 135 km at an average speed of 90 km/h:</p><p><strong>Time = 135 ÷ 90 = 1.5 h = 1 h 30 min.</strong></p></section>
<section><p className="eyebrow">5 · AVERAGE SPEED FOR A WHOLE JOURNEY</p><h2>Add the distances and times first</h2><p>A vehicle covers 40 km in 1 hour, then 80 km in 1 hour.</p><div className="formula">Average speed = (40 + 80) ÷ (1 + 1) = 60 km/h</div><p>If the stages take different lengths of time, simply averaging their speeds generally gives the wrong result. Always use <strong>total distance ÷ total time</strong>. Include a stop when the question asks for the average over the whole elapsed journey.</p></section>
<section id="practice"><p className="eyebrow">6 · CHECK YOUR UNDERSTANDING</p><h2>Rates practice</h2><p>Enter numbers only; each unit is already shown. You may retry each question.</p><p aria-live="polite"><strong>{score} of {questions.length} correct</strong> · {Object.values(checked).filter(Boolean).length} checked</p>{questions.map((q,i)=><article className="question" key={q.id}><label htmlFor={q.id}>{i+1}. {q.prompt}</label><div className="answerRow"><input id={q.id} inputMode="decimal" value={answers[q.id]??""} onChange={e=>{setAnswers({...answers,[q.id]:e.target.value});setChecked({...checked,[q.id]:false})}} aria-describedby={`${q.id}-unit`}/><span id={`${q.id}-unit`}>{q.unit}</span><button type="button" onClick={()=>setChecked({...checked,[q.id]:true})}>Check</button></div>{checked[q.id]&&<p role="status" className={matches(answers[q.id]??"",q.answer)?"success":"note"}>{matches(answers[q.id]??"",q.answer)?`Correct. ${q.working}`:`Not yet. ${q.hint}`}</p>}<details><summary>Show worked solution</summary><p>{q.working}</p></details></article>)}<button type="button" onClick={()=>{setAnswers({});setChecked({})}}>Reset practice</button><p className="note">These practice answers are for this page session and reset when the page reloads.</p></section>
<section className="summary"><p className="eyebrow">SECTION SUMMARY</p><h2>Four checks for every rate problem</h2><ol><li>Identify what is being measured per unit of what.</li><li>Convert quantities to compatible units.</li><li>Choose the calculation and keep the unit in the answer.</li><li>Check whether the result is reasonable.</li></ol><Link href="/maths/s2/chapter-8" className="back">Finish Section 8.1 →</Link></section>
<style jsx>{`
.ratesPage{max-width:1100px;width:calc(100% - 40px);margin:35px auto 70px;color:#24364b;font:17px/1.65 Arial,sans-serif}.ratesPage *{box-sizing:border-box}.ratesPage :global(.back){color:#0f766e;text-decoration:none;font-weight:700;display:inline-block;margin-bottom:20px}header{padding:38px;background:#fff4e5;border:1px solid #fed7aa;border-radius:25px}.eyebrow{color:#a64e10;font-size:13px;letter-spacing:.12em;font-weight:800;margin:0 0 12px}h1{font-size:clamp(38px,6vw,58px);line-height:1.1;margin:0 0 18px}h2{font-size:28px;line-height:1.3;margin:0 0 18px}h3{font-size:21px;margin:0 0 12px}section{padding:30px;border:1px solid #dce5ee;border-radius:22px;background:white;margin-top:24px;scroll-margin-top:20px}.grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:18px;margin:22px 0}.two{grid-template-columns:repeat(2,minmax(0,1fr))}.grid article{background:#f6f8fc;padding:22px;border-radius:15px}.formula{padding:20px;background:#edf9f5;color:#115e59;border-radius:14px;font-weight:700;font-size:20px;text-align:center}.note{background:#fff7ed;padding:15px;border-radius:12px;color:#85430f}.success{background:#e7f8ee;padding:15px;border-radius:12px;color:#12643a}.tags,.choices{display:flex;gap:12px;flex-wrap:wrap}.tags a{padding:8px 18px;background:white;color:#965016;border-radius:10px;text-decoration:none;font-weight:700}button{border:1px solid #6d3eb3;background:#6d3eb3;color:white;border-radius:10px;padding:11px 18px;font:inherit;font-weight:700;cursor:pointer}button[aria-pressed=true]{background:#0f766e;border-color:#0f766e}input{font:inherit;border:1px solid #94a3b8;border-radius:9px;padding:9px;min-width:0}input[type=range]{width:100%;display:block;accent-color:#0f766e;margin-top:15px}label{display:block;font-weight:700}.diagram{overflow-x:auto}.question{padding:24px;background:#f8fafc;border:1px solid #e1e8ef;border-radius:15px;margin:18px 0}.answerRow{display:flex;align-items:center;gap:12px;flex-wrap:wrap;margin-top:15px}.answerRow input{width:150px}details{margin-top:16px}summary{cursor:pointer;color:#6d3eb3;font-weight:700}.summary{background:#f0fdfa}:focus-visible{outline:3px solid #ed9e34;outline-offset:3px}@media(max-width:750px){.grid,.two{grid-template-columns:1fr}header,section{padding:24px}}@media(max-width:450px){.ratesPage{width:calc(100% - 24px);font-size:16px}header,section{padding:19px}.formula{font-size:18px}.question{padding:17px}}
`}</style></main>;
}
