"use client";

import { useState } from "react";
import Link from "next/link";
import { SquareModel, CubeModel, RootNumberLine } from "@/components/maths/S2Chapter11Roots";

const questions = [
  {q:"Evaluate √81.", choices:["−9","9","±9"], correct:1, why:"√81 is the principal square root: 9. It is not ±9."},
  {q:"Find all real solutions of x² = 81.", choices:["x = 9 only","x = −9 only","x = 9 or −9"], correct:2, why:"Both 9² and (−9)² equal 81."},
  {q:"Evaluate ∛(−216).", choices:["−6","6","No real value"], correct:0, why:"(−6)³ = −216, so the cube root is −6."},
  {q:"Evaluate the principal fourth root of 625.", choices:["±5","5","25"], correct:1, why:"5⁴ = 625. The principal fourth root is the non-negative value, 5."},
  {q:"How many real solutions does x⁴ = −16 have?", choices:["Two","One","None"], correct:2, why:"An even power of a real number cannot be negative."},
  {q:"Evaluate √(49/100).", choices:["7/10","49/10","±7/10"], correct:0, why:"(7/10)² = 49/100, and 7/10 is non-negative."},
  {q:"Evaluate −√36.", choices:["6","−6","No real value"], correct:1, why:"The minus sign is outside the root: −√36 = −6."},
  {q:"Evaluate √((−8)²).", choices:["−8","±8","8"], correct:2, why:"First (−8)² = 64; then √64 = 8."},
  {q:"Which two consecutive integers contain √30 between them?", choices:["5 and 6","15 and 16","4 and 5"], correct:0, why:"5² = 25 < 30 < 36 = 6², so 5 < √30 < 6."},
  {q:"Evaluate ∛0.", choices:["No real value","0","±1"], correct:1, why:"0³ = 0. Zero has exactly one real cube root: 0."},
  {q:"Round √7 to 3 significant figures.", choices:["2.646","2.64","2.65"], correct:2, why:"√7 = 2.645751… The fourth significant digit is 5, so the answer is 2.65."},
  {q:"A cube has volume 343 cm³. Find its edge length.", choices:["7 cm","±7 cm","49 cm"], correct:0, why:"The edge length is ∛343 = 7 cm. A physical length is positive."},
];

export default function NthRootsLesson() {
  const [side,setSide] = useState(4);
  const [answers,setAnswers] = useState<Record<number,number>>({});
  const attempted = Object.keys(answers).length;
  const score = questions.filter((q,i)=>answers[i]===q.correct).length;
  return <main className="lesson">
    <Link href="/maths/s2/chapter-11">← Chapter 11 overview</Link>
    <header><p className="eyebrow">S2 · CHAPTER 11 · SECTION 11.1</p><h1>Concept of nth Roots</h1><p>Reverse powers, interpret root symbols and find real roots accurately.</p></header>
    <section><h2>Learning goals</h2><ul><li>Connect an nth root with the equation xⁿ = a.</li><li>Distinguish a principal root from all the solutions of an equation.</li><li>Use even and odd powers to decide which real roots exist.</li><li>Find exact roots and estimate or round non-exact roots.</li></ul><p className="note">Throughout this lesson, n is a positive integer with n ≥ 2, and we work only with real numbers.</p></section>
    <section><h2>1. A root reverses a power</h2><p>Raising a number to a power multiplies repeated copies of that number. Finding a root asks which number could have produced the result.</p><p className="formula">If xⁿ = a, then x is an nth root of a.</p><p>For example, 2⁵ = 32, so 2 is a fifth root of 32. The small number n in ⁿ√a is the <strong>index</strong>; a is the number under the radical. For square roots, the index 2 is usually omitted.</p><div className="grid"><article><h3>Square: area to side length</h3><SquareModel side={side}/><p>Area = {side}² = {side*side} square units.</p><p>Side length = √{side*side} = {side} units.</p></article><article><h3>Cube: volume to edge length</h3><CubeModel side={side}/><p>Volume = {side}³ = {side**3} cubic units.</p><p>Edge length = ∛{side**3} = {side} units.</p></article></div><label htmlFor="side">Choose a side length: {side} units</label><input id="side" type="range" min="1" max="6" step="1" value={side} onChange={e=>setSide(Number(e.target.value))}/><p className="note">The drawings are schematic; the square grid shows one square unit per cell. A length is never negative.</p></section>
    <section><h2>2. Square roots: one symbol, two possible solutions</h2><p>Both 6² = 36 and (−6)² = 36. Therefore, the two square roots of 36 are 6 and −6.</p><RootNumberLine/><div className="grid"><article><h3>Evaluate an expression</h3><p className="formula">√36 = 6</p><p>The radical √36 denotes the <strong>principal square root</strong>: the non-negative square root.</p></article><article><h3>Solve an equation</h3><p className="formula">x² = 36 → x = ±6</p><p>The symbol ± means “plus or minus”. Here, it gives two solutions: x = 6 or x = −6.</p></article></div><p className="warning">Do not write √36 = ±6. The expression has one value; the equation has two solutions.</p><p>Zero is a special case: √0 = 0, and x² = 0 has only one solution, x = 0.</p></section>
    <section><h2>3. Cube roots and higher roots</h2><p>An odd power preserves the sign of its base. For example, (−4)³ = −64, so ∛(−64) = −4.</p><p className="formula">∛125 = 5 &nbsp; · &nbsp; ∛(−125) = −5</p><p>With an even index and a positive number, the radical denotes the non-negative root. For example, ⁴√81 = 3, but x⁴ = 81 has solutions x = ±3.</p><div className="tableWrap"><table><caption>Number of real solutions of xⁿ = a</caption><thead><tr><th scope="col">Index n</th><th scope="col">a &gt; 0</th><th scope="col">a = 0</th><th scope="col">a &lt; 0</th></tr></thead><tbody><tr><th scope="row">Even</th><td>Two: one positive, one negative</td><td>One: 0</td><td>No real solutions</td></tr><tr><th scope="row">Odd</th><td>One positive solution</td><td>One: 0</td><td>One negative solution</td></tr></tbody></table></div><p className="warning">√(−16) has no real value, but −√16 = −4. Check whether the minus sign is inside or outside the root.</p></section>
    <section><h2>4. Worked examples</h2><p className="note">The Reference column below contains explanatory reasons written for this lesson, not claimed textbook abbreviations. No geometric theorem is needed in this section.</p><div className="tableWrap"><table><caption>Example A · Evaluate √0.64</caption><thead><tr><th scope="col">Working</th><th scope="col">Reference</th></tr></thead><tbody><tr><td>0.8² = 0.64</td><td>Check by squaring</td></tr><tr><td>√0.64 = 0.8</td><td>Principal square root</td></tr></tbody></table></div><div className="tableWrap"><table><caption>Example B · Solve x⁴ = 16</caption><thead><tr><th scope="col">Working</th><th scope="col">Reference</th></tr></thead><tbody><tr><td>2⁴ = 16 and (−2)⁴ = 16</td><td>Check both signs</td></tr><tr><td>x = 2 or x = −2</td><td>All real fourth roots of 16</td></tr></tbody></table></div><div className="grid"><article><h3>Example C · A fraction</h3><p>Evaluate ∛(−8/27).</p><p>(−2/3)³ = −8/27</p><p className="formula">∛(−8/27) = −2/3</p></article><article><h3>Example D · A square</h3><p>A square has area 196 cm². Find its side length.</p><p className="formula">Side length = √196 = 14 cm</p><p>Use cm for length, not cm². Discard the negative solution because this is a length.</p></article></div></section>
    <section><h2>5. Estimate before using a calculator</h2><p>Locate the number between nearby perfect powers.</p><p className="formula">4² &lt; 19 &lt; 5², so 4 &lt; √19 &lt; 5.</p><p>A calculator gives √19 = 4.358898… Therefore √19 ≈ 4.36 to 3 significant figures. The exact answer is still √19.</p><p>For cube roots, 2³ &lt; 20 &lt; 3³ tells us 2 &lt; ∛20 &lt; 3. Also, (−3)³ &lt; −20 &lt; (−2)³ tells us −3 &lt; ∛(−20) &lt; −2.</p><ol><li>Choose the square-root or nth-root function on your calculator.</li><li>For an nth root, check the index and put a negative radicand in parentheses.</li><li>Check the sign and size against your estimate.</li><li>Keep extra digits during working; round only the final answer.</li></ol><p className="note">Calculator layouts differ. If a fractional-power entry rejects a negative number, use the dedicated odd-root function, or find the root of its positive magnitude and then apply the minus sign.</p></section>
    <section><h2>6. Common mistakes</h2><ul><li><strong>√(x²) is not always x.</strong> For real x, √(x²) = |x|. For example, √((−7)²) = √49 = 7.</li><li><strong>Brackets matter.</strong> (−5)² = 25, whereas −5² = −25.</li><li><strong>Do not split a sum.</strong> √(9 + 16) = √25 = 5, not √9 + √16 = 7.</li><li><strong>Read the instruction.</strong> “Evaluate √49” asks for 7; “find the square roots of 49” asks for 7 and −7.</li></ul></section>
    <section id="practice"><h2>7. Check your understanding</h2><p>Answer each question once, then read its explanation. Use “Restart practice” for a fresh attempt.</p><p className="score" role="status">Answered {attempted} of {questions.length} · Correct {score} of {attempted}</p><p className="note">Practice is temporary on this page. It does not save progress or award XP.</p>{questions.map((q,i)=><fieldset key={q.q}><legend>{i+1}. {q.q}</legend><div className="choices">{q.choices.map((choice,j)=><button type="button" key={choice} disabled={answers[i]!==undefined} aria-pressed={answers[i]===j} onClick={()=>setAnswers(previous=>previous[i]!==undefined?previous:{...previous,[i]:j})}>{choice}</button>)}</div>{answers[i]!==undefined&&<p className={answers[i]===q.correct?"correct":"feedback"} role="status"><strong>{answers[i]===q.correct?"Correct. ":"Not quite. "}</strong>{q.why}</p>}</fieldset>)}{attempted===questions.length&&<p className="formula" role="status">Practice complete: {score} / {questions.length}. {score===questions.length?"You are ready to move on.":"Review the explanations and try again when ready."}</p>}<button type="button" onClick={()=>{setAnswers({});document.getElementById('practice')?.scrollIntoView({behavior:'smooth'});}}>Restart practice</button></section>
    <section><h2>Before you leave</h2><p>Can you explain why √64 = 8, but x² = 64 gives x = ±8? Can you explain why ∛(−64) is real but √(−64) is not?</p><Link href="/maths/s2/chapter-11">← Back to Chapter 11</Link><p><Link href="/maths/s2/chapter-11/pythagoras-theorem-and-applications">Next: 11.2 Pythagoras’ Theorem and its Applications →</Link></p></section>
    <style jsx>{`
      .lesson{max-width:1080px;width:calc(100% - 32px);margin:36px auto 70px;color:#24364b;font:18px/1.65 Arial,sans-serif}.lesson *{box-sizing:border-box}.lesson :global(a){color:#0f766e;font-weight:700}header{padding:36px;background:#ecfeff;border:1px solid #a5f3fc;border-radius:26px;margin-top:22px}h1{font-size:clamp(34px,5vw,52px);line-height:1.15}h2{font-size:28px;line-height:1.3}h3{font-size:21px;line-height:1.4}.eyebrow{font-size:13px;font-weight:800;letter-spacing:.1em;color:#0e7490}section{padding:30px;border:1px solid #dce5ee;border-radius:22px;margin-top:24px;background:white}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:20px}.grid article{padding:22px;background:#f8fafc;border-radius:14px;min-width:0}.formula{padding:18px;background:#f5f3ff;color:#5b21b6;border-radius:12px;font-weight:700;overflow-wrap:anywhere}.note{font-size:15px;color:#52647a}.warning{background:#fff7ed;border-left:4px solid #c2410c;padding:16px}.tableWrap{overflow:auto;margin:22px 0}table{width:100%;border-collapse:collapse;text-align:left;font-size:16px}caption{text-align:left;font-weight:700;padding:8px 0}th,td{border:1px solid #dce5ee;padding:13px;vertical-align:top}th{background:#ecfeff}label{display:block;font-weight:700}input{width:100%;min-height:44px;accent-color:#0f766e}fieldset{min-width:0;margin:24px 0;padding:20px;border:1px solid #cbd5e1;border-radius:14px}legend{font-weight:700;padding:0 8px;max-width:100%}.choices{display:flex;flex-wrap:wrap;gap:12px}button{min-height:46px;padding:12px 18px;font:inherit;border:1px solid #0f766e;color:#0f766e;background:white;border-radius:12px;cursor:pointer}button[aria-pressed=true]{background:#0f766e;color:white}button:disabled{cursor:default}button:disabled:not([aria-pressed=true]){color:#52647a;border-color:#cbd5e1}.correct{color:#166534}.feedback{color:#9a3412}.score{font-weight:700}button:focus-visible,input:focus-visible,.lesson :global(a:focus-visible){outline:3px solid #d97706;outline-offset:3px}li{margin-bottom:8px}@media(max-width:720px){.grid{grid-template-columns:1fr}header,section{padding:22px}.lesson{font-size:17px}fieldset{padding:15px}th,td{padding:10px}}
    `}</style>
  </main>;
}
