"use client";
import {useState} from "react";
import Link from "next/link";
import {Diagram,Angle,type Point} from "@/components/maths/S2Chapter10Geometry";
const ref="∠s at a pt.";
const questions=[
{q:"How many equilateral triangles meet at a vertex in their regular tessellation?",a:6,unit:"triangles",why:"360° ÷ 60° = 6."},
{q:"How many squares meet at a vertex in their regular tessellation?",a:4,unit:"squares",why:"360° ÷ 90° = 4."},
{q:"How many regular hexagons meet at a vertex in their regular tessellation?",a:3,unit:"hexagons",why:"360° ÷ 120° = 3."},
{q:"Find each interior angle of a regular pentagon.",a:108,unit:"°",why:"(5 − 2) × 180° ÷ 5 = 108°."},
{q:"Three regular pentagons share a vertex without overlap. Find the remaining gap angle.",a:36,unit:"°",why:"360° − 3 × 108° = 36°."},
{q:"Two regular octagon corners and one square corner meet at a vertex. Find their total angle.",a:360,unit:"°",why:"135° + 135° + 90° = 360°."},
{q:"A triangle has angles 42° and 73°. Find its third angle.",a:65,unit:"°",why:"180° − 42° − 73° = 65°. A triangle can tessellate even if its angles differ."},
{q:"Four angles of a quadrilateral are placed together at a point. What is their total?",a:360,unit:"°",why:"(4 − 2) × 180° = 360°. Every simple quadrilateral can tessellate."}
];
const colors=['#ccfbf1','#ede9fe','#fef3c7','#dbeafe'];
function Tile({points,index}:{points:Point[];index:number}){return <polygon points={points.map(p=>`${p.x},${p.y}`).join(' ')} fill={colors[index%4]} stroke="#24364b" strokeWidth={1.5}/>}
function CornerDiagram({n}:{n:number}){const alpha=(n-2)*180/n,count=Math.floor(360/alpha),v={x:260,y:170},rad=alpha*Math.PI/180;return <Diagram label={`${count} regular ${n}-gon corners of ${alpha} degrees meeting at a vertex${n===5?', leaving a 36 degree gap':''}. Only the corner regions are shown.`} height={340}>{Array.from({length:count},(_,i)=>{const a=-Math.PI/2+i*rad,b=a+rad,p={x:v.x+125*Math.cos(a),y:v.y+125*Math.sin(a)},q={x:v.x+125*Math.cos(b),y:v.y+125*Math.sin(b)};return <g key={i}><Tile points={[v,p,q]} index={i}/><Angle v={v} a={p} b={q} r={24} label={`${alpha}°`} labelR={43}/></g>})}{n===5&&<g><path d="M160 55 L230 95" stroke="#b45309" fill="none"/><text x={80} y={50} fontSize={17} fill="#b45309">36° gap</text></g>}</Diagram>}
function Pattern({kind}:{kind:'triangle'|'square'|'hexagon'}){const tiles:Point[][]=[];if(kind==='square'){for(let r=0;r<3;r++)for(let c=0;c<5;c++)tiles.push([{x:85+c*70,y:45+r*70},{x:155+c*70,y:45+r*70},{x:155+c*70,y:115+r*70},{x:85+c*70,y:115+r*70}]);}else if(kind==='triangle'){const h=70*Math.sqrt(3)/2;for(let r=0;r<3;r++)for(let c=0;c<5;c++){const x=45+c*70+r*35,y=50+r*h;tiles.push([{x,y},{x:x+70,y},{x:x+35,y:y+h}],[{x:x+70,y},{x:x+105,y:y+h},{x:x+35,y:y+h}]);}}else{const s=42,h=Math.sqrt(3)*s;for(let c=0;c<5;c++)for(let r=0;r<3;r++){const x=120+c*1.5*s,y=60+r*h+(c%2)*h/2;tiles.push(Array.from({length:6},(_,i)=>({x:x+s*Math.cos(i*Math.PI/3),y:y+s*Math.sin(i*Math.PI/3)})));}}return <Diagram label={`A finite patch of a tessellation by ${kind==='triangle'?'equilateral triangles':kind==='square'?'squares':'regular hexagons'}. The pattern continues beyond its boundary.`} height={330}>{tiles.map((points,i)=><Tile key={i} points={points} index={i}/>)}</Diagram>}
function TrianglePattern(){const tiles:Point[][]=[];for(let r=0;r<3;r++)for(let c=0;c<3;c++){const a={x:65+c*115+r*25,y:45+r*75},b={x:a.x+115,y:a.y},d={x:a.x+25,y:a.y+75},e={x:a.x+140,y:a.y+75};tiles.push([a,b,d],[b,e,d]);}return <Diagram label="Congruent scalene triangles paired into parallelograms and repeated by translation." height={320}>{tiles.map((points,i)=><Tile key={i} points={points} index={i}/>)}</Diagram>}
function Practice(){const [values,setValues]=useState<string[]>(questions.map(()=>''));const [checked,setChecked]=useState(false);const correct=(i:number)=>values[i].trim()!==''&&Number.isFinite(Number(values[i]))&&Math.abs(Number(values[i])-questions[i].a)<0.000001;return <section><h2>Check your understanding</h2><p>Enter numbers only; the units are shown beside each box.</p>{questions.map((q,i)=><div className="question" key={q.q}><label htmlFor={'q'+i}>{i+1}. {q.q}</label><div><input id={'q'+i} type="text" inputMode="decimal" value={values[i]} onChange={e=>{setValues(values.map((v,j)=>j===i?e.target.value:v));setChecked(false)}}/> <span>{q.unit}</span></div>{checked&&<p>{correct(i)?'Correct.':values[i].trim()===''?'Not answered.':'Try again.'} {q.why}</p>}</div>)}<button onClick={()=>setChecked(true)}>Check answers</button> <button onClick={()=>{setValues(questions.map(()=>''));setChecked(false)}}>Reset</button>{checked&&<p role="status">{questions.filter((_,i)=>correct(i)).length} of {questions.length} correct. Use the reference: {ref}.</p>}</section>}
export default function Tessellation(){const [kind,setKind]=useState<'triangle'|'square'|'hexagon'>('triangle');return <main className="s2c10s3"><Link href="/maths/s2/chapter-10">← Chapter 10: Polygons</Link><header><p className="eyebrow">S2 · CHAPTER 10 · SECTION 10.3</p><h1>Tessellation of Figures</h1><p>Explore how copies of a shape can cover a plane without gaps or overlaps.</p></header>
<section><h2>1. What is a tessellation?</h2><p>A tessellation is a repeating covering of the plane with no gaps and no overlaps. We draw a finite patch, but the pattern must be able to continue.</p><p>Tiles may be translated (slid), rotated (turned) or reflected (flipped). Their shape and size stay unchanged.</p><p>A regular tessellation uses one kind of congruent regular polygon, arranged edge-to-edge.</p></section>
<section><h2>2. Explore three regular tessellations</h2><div>{(['triangle','square','hexagon'] as const).map(k=><button key={k} aria-pressed={kind===k} onClick={()=>setKind(k)}>{k==='triangle'?'Equilateral triangles':k==='square'?'Squares':'Regular hexagons'}</button>)}</div><Pattern kind={kind}/><p>The outer boundary is just the edge of the patch shown. Continue the same pattern to cover more of the plane.</p></section>
<section><h2>3. Angles around a vertex</h2><p>The tile corners meeting at a point must add to exactly 360°.</p><p className="reference">Reference: ∠s at a pt.</p><p>The following diagrams show <strong>corner regions only</strong>, not whole tiles.</p><h3>Equilateral triangles</h3><CornerDiagram n={3}/><p>6 × 60° = 360°, so six corners fit around a vertex.</p><h3>Squares</h3><CornerDiagram n={4}/><p>4 × 90° = 360°, so four corners fit.</p><h3>Regular hexagons</h3><CornerDiagram n={6}/><p>3 × 120° = 360°, so three corners fit.</p></section>
<section><h2>4. Why not regular pentagons?</h2><CornerDiagram n={5}/><table><thead><tr><th>Working</th><th>Reference / reason</th></tr></thead><tbody><tr><td>Interior angle = (5 − 2) × 180° ÷ 5 = 108°</td><td>∠ sum of polygon; equal interior angles</td></tr><tr><td>3 × 108° = 324°</td><td>Three corners leave a gap</td></tr><tr><td>Gap = 360° − 324° = 36°</td><td>∠s at a pt.</td></tr><tr><td>4 × 108° = 432° &gt; 360°</td><td>Four corners overlap</td></tr></tbody></table><p>Regular pentagons alone cannot form a regular edge-to-edge tessellation. Some irregular pentagons can tessellate: do not apply this conclusion to every pentagon.</p></section>
<section><h2>5. Which regular polygons work?</h2><p>For n ≥ 7, each interior angle is greater than 120° and less than 180°. Two corners leave a gap, while three or more exceed 360°.</p><p>For regular pentagons the 108° corners do not fit; triangles, squares and hexagons do. These are the only regular polygons that form a tessellation using one kind of regular polygon alone.</p><p>Checking 360° at a point is necessary. For more complicated combinations, also check that the edges match and the pattern continues without gaps or overlaps.</p></section>
<section><h2>6. All triangles and quadrilaterals</h2><h3>Any triangle can tessellate</h3><TrianglePattern/><p>Rotate a copy of a triangle through 180° about the midpoint of one side. The pair forms a parallelogram. Repeat that parallelogram by translation to tile the plane.</p><p>The triangle need not be equilateral. The diagram uses congruent scalene triangles.</p><h3>Any simple quadrilateral can tessellate</h3><p>A quadrilateral has angle sum 360° [∠ sum of polygon]. Copies can be arranged so that its four different corner angles meet at a point. Half-turns about side midpoints produce matching neighbours, and the arrangement can be continued.</p><p>This includes irregular quadrilaterals. A simple quadrilateral has sides that do not cross.</p></section>
<section><h2>7. Worked example: mixing regular polygons</h2><p>Can two regular octagon corners and one square corner fit around a vertex?</p><table><thead><tr><th>Working</th><th>Reference / reason</th></tr></thead><tbody><tr><td>Each octagon angle = (8 − 2) × 180° ÷ 8 = 135°</td><td>∠ sum of polygon; equal interior angles</td></tr><tr><td>135° + 135° + 90° = 360°</td><td>Calculation</td></tr><tr><td>The three corners fit around a point.</td><td>∠s at a pt.</td></tr></tbody></table><p>Regular octagons and squares of matching side length do form a tessellation. It uses two kinds of regular polygons, so it is not a regular tessellation as defined above.</p></section><Practice/><p><Link href="/maths/s2/chapter-10/sum-of-exterior-angles">← Section 10.2</Link> · <Link href="/maths/s2/chapter-10">Chapter overview</Link></p><style jsx global>{`
.s2c10s3{max-width:1050px;width:calc(100% - 32px);margin:32px auto 70px;color:#24364b;font-family:Arial,sans-serif;line-height:1.7}.s2c10s3 *{box-sizing:border-box}.s2c10s3 a{color:#0f766e;font-weight:700}.s2c10s3 header{background:#ecfeff;border:1px solid #a5f3fc;padding:32px;border-radius:24px;margin-top:24px}.s2c10s3 h1{font-size:clamp(32px,5vw,48px);line-height:1.2}.s2c10s3 h2{font-size:27px;line-height:1.35}.s2c10s3 section{padding:28px;border:1px solid #dce5ee;border-radius:20px;background:#fff;margin:24px 0}.s2c10s3 .eyebrow{color:#0e7490;font-weight:700;font-size:13px;letter-spacing:.08em}.s2c10s3 svg{max-width:580px;margin:20px auto}.s2c10s3 .formula{background:#f5f3ff;color:#5b21b6;padding:16px;border-radius:12px;font-weight:700}.s2c10s3 .reference{font-family:Georgia,serif;font-style:italic}.s2c10s3 table{border-collapse:collapse;width:100%;table-layout:fixed}.s2c10s3 td,.s2c10s3 th{border:1px solid #dce5ee;padding:12px;text-align:left;overflow-wrap:anywhere}.s2c10s3 th{background:#f0fdfa}.s2c10s3 td:first-child,.s2c10s3 th:first-child{width:65%}.s2c10s3 label{display:block;font-weight:700}.s2c10s3 input[type=range]{width:100%;min-height:40px;accent-color:#0f766e}.s2c10s3 .question{padding:20px 0;border-bottom:1px solid #e2e8f0}.s2c10s3 input[type=text]{width:140px;padding:10px;font:inherit;border:1px solid #64748b;border-radius:8px;margin:10px 0}.s2c10s3 button{padding:12px 20px;border:1px solid #0f766e;background:#0f766e;color:white;font:inherit;border-radius:10px;margin-top:18px;cursor:pointer}.s2c10s3 button:focus-visible,.s2c10s3 input:focus-visible{outline:3px solid #d97706;outline-offset:3px}@media(max-width:600px){.s2c10s3 section,.s2c10s3 header{padding:18px}.s2c10s3 td,.s2c10s3 th{padding:8px;font-size:14px}}
`}</style></main>}
