"use client";
import { reasonRef } from "@/data/maths/reasons/reasonBank";
import { DualReason, ReasonContent } from "@/components/maths/DualReason";


import {useState} from "react";
import Link from "next/link";
import {Diagram,Angle,Segment,Vertex} from "@/components/maths/S2Chapter10Geometry";
const ref=reasonRef("polygon.exteriorAngleSum");
const questions=[
{q:"Find the sum of one set of exterior angles of a convex heptagon.",a:360,unit:"°",why:"One exterior angle at each vertex, taken in the same direction, totals 360°." + reasonRef("polygon.exteriorAngleSum")},
{q:"An interior angle is 127°. Find its adjacent exterior angle.",a:53,unit:"°",why:"180° − 127° = 53° " + reasonRef("angles.straightLine", {"variant":"textbook1"}) + "."},
{q:"Find each exterior angle of a regular nonagon (9 sides).",a:40,unit:"°",why:"360° ÷ 9 = 40°. The exterior angles are equal." + reasonRef("polygon.exteriorAngleSum") + reasonRef("polygon.regularExteriorAngles")},
{q:"Each exterior angle of a regular polygon is 24°. Find the number of sides.",a:15,unit:"sides",why:"360° ÷ 24° = 15." + reasonRef("polygon.exteriorAngleSum") + reasonRef("polygon.regularExteriorAngles")},
{q:"Four exterior angles of a convex pentagon are 50°, 60°, 80° and 95°. Find the remaining exterior angle.",a:75,unit:"°",why:"360° − (50° + 60° + 80° + 95°) = 75°." + reasonRef("polygon.exteriorAngleSum")},
{q:"Find each interior angle of a regular dodecagon (12 sides).",a:150,unit:"°",why:"Each exterior angle = 360° ÷ 12 = 30°. Interior angle = 180° − 30° = 150°." + reasonRef("polygon.exteriorAngleSum") + reasonRef("polygon.regularExteriorAngles") + reasonRef("angles.straightLine", {"variant":"textbook1"})},
{q:"Each interior angle of a regular polygon is 156°. Find the number of sides.",a:15,unit:"sides",why:"Each exterior angle = 24°, so n = 360 ÷ 24 = 15." + reasonRef("angles.straightLine", {"variant":"textbook1"}) + reasonRef("polygon.exteriorAngleSum") + reasonRef("polygon.regularExteriorAngles")},
{q:"The exterior angles of a convex quadrilateral are x°, 2x°, 3x° and 4x°. Find x.",a:36,unit:"",why:"10x = 360, so x = 36. Each resulting exterior angle is less than 180°." + reasonRef("polygon.exteriorAngleSum")}
];
function ExteriorDiagram({n=5}:{n?:number}){const pts=Array.from({length:n},(_,i)=>({x:260+100*Math.cos(-Math.PI/2+i*2*Math.PI/n),y:180+100*Math.sin(-Math.PI/2+i*2*Math.PI/n)}));return <Diagram label={`Regular ${n}-gon. Each purple exterior angle is ${360/n} degrees between the incoming side extended and the next side.`} height={380}><polygon points={pts.map(p=>`${p.x},${p.y}`).join(' ')} stroke="#24364b" strokeWidth={2.5} fill="#f0fdfa"/>{pts.map((v,i)=>{const prev=pts[(i+n-1)%n],next=pts[(i+1)%n],len=Math.hypot(v.x-prev.x,v.y-prev.y),ext={x:v.x+(v.x-prev.x)/len*65,y:v.y+(v.y-prev.y)/len*65};return <g key={i}><Segment a={v} b={ext} dashed/><Angle v={v} a={ext} b={next} r={23} label={n<=6?`${Math.round(360/n*10)/10}°`:undefined} labelR={43}/></g>})}</Diagram>}
function PairDiagram(){const v={x:250,y:230},left={x:90,y:230},right={x:430,y:230},ray={x:250+170*Math.cos(-Math.PI/3),y:230+170*Math.sin(-Math.PI/3)};return <Diagram label="A, B and D lie on a straight line. Interior angle ABC is 120 degrees and adjacent exterior angle CBD is 60 degrees." height={300}><Segment a={left} b={right}/><Segment a={v} b={ray}/><Angle v={v} a={left} b={ray} r={30} label="120°" labelR={63}/><Angle v={v} a={ray} b={right} r={38} label="60°" labelR={75}/><Vertex p={left} label="A" dy={25}/><Vertex p={v} label="B" dy={25}/><Vertex p={right} label="D" dy={25}/><Vertex p={ray} label="C" dy={-12}/></Diagram>}
function Practice(){const [values,setValues]=useState<string[]>(questions.map(()=>''));const [checked,setChecked]=useState(false);const correct=(i:number)=>values[i].trim()!==''&&Number.isFinite(Number(values[i]))&&Math.abs(Number(values[i])-questions[i].a)<0.000001;return <section><h2>Check your understanding</h2><p>Enter numbers only; the units are shown beside each box.</p>{questions.map((q,i)=><div className="question" key={q.q}><label htmlFor={'q'+i}>{i+1}. {q.q}</label><div><input id={'q'+i} type="text" inputMode="decimal" value={values[i]} onChange={e=>{setValues(values.map((v,j)=>j===i?e.target.value:v));setChecked(false)}}/> <span>{q.unit}</span></div>{checked&&<p>{correct(i)?'Correct.':values[i].trim()===''?'Not answered.':'Try again.'} <ReasonContent>{q.why}</ReasonContent></p>}</div>)}<button onClick={()=>setChecked(true)}>Check answers</button> <button onClick={()=>{setValues(questions.map(()=>''));setChecked(false)}}>Reset</button>{checked&&<p role="status">{questions.filter((_,i)=>correct(i)).length} of {questions.length} correct. <ReasonContent heading>{ref}</ReasonContent></p>}</section>}
export default function ExteriorAngles(){const [n,setN]=useState(5);return <main className="s2c10s2"><Link href="/maths/s2/chapter-10">← Chapter 10: Polygons</Link><header><p className="eyebrow">S2 · CHAPTER 10 · SECTION 10.2</p><h1>Sum of Exterior Angles of a Convex Polygon</h1><p>Use a complete turn to find exterior angles and the number of sides of a regular polygon.</p></header>
<section><h2>1. Which angle is an exterior angle?</h2><p>Extend one side of a convex polygon through a vertex. The angle between that extension and the adjacent side is an exterior angle.</p><PairDiagram/><p>Here, AB is extended to D. If ∠ABC is the interior angle, ∠CBD is its adjacent exterior angle.</p><p className="formula">Interior angle + adjacent exterior angle = 180°</p><p className="reference"><DualReason reasonId="angles.straightLine" variant="textbook1" heading /></p><p>Use the adjacent exterior angle, not the reflex angle around the outside of the vertex.</p></section>
<section><h2>2. One complete turn</h2><p>Imagine walking around the boundary of a convex polygon. At each vertex, turn from your incoming direction to your outgoing direction. After one circuit, you have made one complete turn.</p><p className="formula">Sum of exterior angles = 360°</p><p className="reference"><ReasonContent heading>{ref}</ReasonContent></p><p>Take <strong>one exterior angle at each vertex, all in the same direction</strong>. Do not count both possible exterior angles at each vertex.</p><label htmlFor="sides">Regular polygon: {n} sides</label><input id="sides" type="range" min={3} max={8} value={n} onChange={e=>setN(Number(e.target.value))}/><ExteriorDiagram n={n}/><p className="formula">{n} × (360° ÷ {n}) = 360°</p><p>The dashed lines extend the incoming sides. Purple arcs show the exterior angles. For 7 or 8 sides, angle labels are omitted to keep the diagram clear.</p><p>This total also holds for irregular convex polygons; their exterior angles need not be equal.</p></section>
<section><h2>3. Why does the formula work?</h2><table><thead><tr><th>Working</th><th>Reason</th></tr></thead><tbody><tr><td>Sum of n interior–exterior pairs = n × 180°</td><td><DualReason reasonId="angles.straightLine" variant="textbook1" /></td></tr><tr><td>Sum of interior angles = (n − 2) × 180°</td><td><DualReason reasonId="polygon.interiorAngleSum" /></td></tr><tr><td>Sum of exterior angles = n × 180° − (n − 2) × 180° = 360°</td><td>Subtract and simplify</td></tr></tbody></table></section>
<section><h2>4. Worked example: a missing exterior angle</h2><p>Four exterior angles of a convex pentagon are 45°, 70°, 85° and 100°. Find the remaining exterior angle x.</p><table><thead><tr><th>Working</th><th>Reason</th></tr></thead><tbody><tr><td>x + 45° + 70° + 85° + 100° = 360°</td><td><ReasonContent>{ref}</ReasonContent></td></tr><tr><td>x = 360° − 300° = 60°</td><td>Calculation</td></tr></tbody></table><p>Use 360°, not the pentagon's interior angle sum of 540°.</p></section>
<section><h2>5. Regular polygons</h2><p>A regular polygon has equal interior angles, so its adjacent exterior angles are equal too.</p><p className="formula">Each exterior angle = 360° ÷ n<br/>Each interior angle = 180° − 360° ÷ n</p><h3>Worked example: a regular octagon</h3><table><thead><tr><th>Working</th><th>Reason</th></tr></thead><tbody><tr><td>8e = 360°</td><td><ReasonContent>{ref}{reasonRef("polygon.regularExteriorAngles")}</ReasonContent></td></tr><tr><td>e = 45°</td><td>Divide by 8</td></tr><tr><td>Interior angle = 180° − 45° = 135°</td><td><DualReason reasonId="angles.straightLine" variant="textbook1" /></td></tr></tbody></table><p>For an irregular polygon, 360° ÷ n is only the average exterior angle.</p></section>
<section><h2>6. Worked example: find the number of sides</h2><p>Each interior angle of a regular polygon is 160°. Find n.</p><table><thead><tr><th>Working</th><th>Reason</th></tr></thead><tbody><tr><td>Each exterior angle = 180° − 160° = 20°</td><td><DualReason reasonId="angles.straightLine" variant="textbook1" /></td></tr><tr><td>n × 20° = 360°</td><td><ReasonContent>{ref}</ReasonContent></td></tr><tr><td>n = 18</td><td>Calculation</td></tr></tbody></table><p>Check: (18 − 2) × 180° ÷ 18 = 160°.</p><h3>Can the answer be a decimal?</h3><p>If each exterior angle were 50°, then n = 360 ÷ 50 = 7.2. A polygon cannot have 7.2 sides, so no regular polygon has an exterior angle of 50°. Do not round the side count.</p></section>
<section><h2>7. Choose the correct total</h2><table><thead><tr><th>What is being added?</th><th>Total</th></tr></thead><tbody><tr><td>All interior angles of an n-gon</td><td>(n − 2) × 180°</td></tr><tr><td>One exterior angle at each vertex of a convex polygon, same turning direction</td><td>360°</td></tr><tr><td>One interior angle and its adjacent exterior angle</td><td>180°</td></tr></tbody></table></section><Practice/><p><Link href="/maths/s2/chapter-10/sum-of-interior-angles">← Section 10.1</Link> · <Link href="/maths/s2/chapter-10">Chapter overview</Link></p><style jsx global>{`
.s2c10s2{max-width:1050px;width:calc(100% - 32px);margin:32px auto 70px;color:#24364b;font-family:Arial,sans-serif;line-height:1.7}.s2c10s2 *{box-sizing:border-box}.s2c10s2 a{color:#0f766e;font-weight:700}.s2c10s2 header{background:#ecfeff;border:1px solid #a5f3fc;padding:32px;border-radius:24px;margin-top:24px}.s2c10s2 h1{font-size:clamp(32px,5vw,48px);line-height:1.2}.s2c10s2 h2{font-size:27px;line-height:1.35}.s2c10s2 section{padding:28px;border:1px solid #dce5ee;border-radius:20px;background:#fff;margin:24px 0}.s2c10s2 .eyebrow{color:#0e7490;font-weight:700;font-size:13px;letter-spacing:.08em}.s2c10s2 svg{max-width:580px;margin:20px auto}.s2c10s2 .formula{background:#f5f3ff;color:#5b21b6;padding:16px;border-radius:12px;font-weight:700}.s2c10s2 .reference{font-family:Georgia,serif;font-style:italic}.s2c10s2 table{border-collapse:collapse;width:100%;table-layout:fixed}.s2c10s2 td,.s2c10s2 th{border:1px solid #dce5ee;padding:12px;text-align:left;overflow-wrap:anywhere}.s2c10s2 th{background:#f0fdfa}.s2c10s2 td:first-child,.s2c10s2 th:first-child{width:65%}.s2c10s2 label{display:block;font-weight:700}.s2c10s2 input[type=range]{width:100%;min-height:40px;accent-color:#0f766e}.s2c10s2 .question{padding:20px 0;border-bottom:1px solid #e2e8f0}.s2c10s2 input[type=text]{width:140px;padding:10px;font:inherit;border:1px solid #64748b;border-radius:8px;margin:10px 0}.s2c10s2 button{padding:12px 20px;border:1px solid #0f766e;background:#0f766e;color:white;font:inherit;border-radius:10px;margin-top:18px;cursor:pointer}.s2c10s2 button:focus-visible,.s2c10s2 input:focus-visible{outline:3px solid #d97706;outline-offset:3px}@media(max-width:600px){.s2c10s2 section,.s2c10s2 header{padding:18px}.s2c10s2 td,.s2c10s2 th{padding:8px;font-size:14px}}
`}</style></main>}
